//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Boletagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Boletagem() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Boletagem", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/boletagem/en-US.
        /// </summary>
        internal static string boletagem_content_tutorial {
            get {
                return ResourceManager.GetString("boletagem_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a DataEntry.
        /// </summary>
        internal static string boletagem_grid1 {
            get {
                return ResourceManager.GetString("boletagem_grid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nova Verba.
        /// </summary>
        internal static string boletagem_grid1_btn1 {
            get {
                return ResourceManager.GetString("boletagem_grid1_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nova Verba.
        /// </summary>
        internal static string boletagem_grid1_btn1_guide {
            get {
                return ResourceManager.GetString("boletagem_grid1_btn1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Novo Boleto.
        /// </summary>
        internal static string boletagem_grid1_btn2 {
            get {
                return ResourceManager.GetString("boletagem_grid1_btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Novo Boleto.
        /// </summary>
        internal static string boletagem_grid1_btn2_guide {
            get {
                return ResourceManager.GetString("boletagem_grid1_btn2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Acesso à área boletas, nessa área é possível visualizar as boletas criadas e ainda não auditadas, além de criar novas boletas manuais ou por débito em conta e também criar e associar novas Verbas.&lt;br/&gt;Para alterar os dados é possível clicando duas vezes na linha desejada, Para Inserir deve-se clicar no ícone + e preencher os campos. Para Excluir é necessário clicar no ícone da lixeira. Após qualquer dessas operações é necessário Salvar ou então Descartar..
        /// </summary>
        internal static string boletagem_grid1_guide {
            get {
                return ResourceManager.GetString("boletagem_grid1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Gravar.
        /// </summary>
        internal static string boletagem_grid1_popup1_btn {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a A Nova Verba será automaticamente associada ao Contrato selecionado.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl1 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Intervalo.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl10 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Entity:.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl2 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contrato:.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl3 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl4 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calcula IFRS?.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl5 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Classificador.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl6 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tipo Receita.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl7 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Periodicidade.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl8 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Recuperação de Impostos.
        /// </summary>
        internal static string boletagem_grid1_popup1_lbl9 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cadastro Nova Verba.
        /// </summary>
        internal static string boletagem_grid1_popup1_titulo {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup1_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Prosseguir.
        /// </summary>
        internal static string boletagem_grid1_popup2_btn1 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Concluir.
        /// </summary>
        internal static string boletagem_grid1_popup2_btn2 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Limpar.
        /// </summary>
        internal static string boletagem_grid1_popup2_btn3 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Boleto Bancário.
        /// </summary>
        internal static string boletagem_grid1_popup2_combo1_item1 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_combo1_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a TED/PIX.
        /// </summary>
        internal static string boletagem_grid1_popup2_combo1_item2 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_combo1_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Débito em Conta.
        /// </summary>
        internal static string boletagem_grid1_popup2_combo1_item3 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_combo1_item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Verbas.
        /// </summary>
        internal static string boletagem_grid1_popup2_grid_col1 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string boletagem_grid1_popup2_grid_col2 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Forma de Pagamento.
        /// </summary>
        internal static string boletagem_grid1_popup2_lbl1 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Entity:.
        /// </summary>
        internal static string boletagem_grid1_popup2_lbl2 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecione o Contrato.
        /// </summary>
        internal static string boletagem_grid1_popup2_lbl3 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome Novo Boleto.
        /// </summary>
        internal static string boletagem_grid1_popup2_lbl4 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Valor Total.
        /// </summary>
        internal static string boletagem_grid1_popup2_lbl5 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vencimento.
        /// </summary>
        internal static string boletagem_grid1_popup2_lbl6 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Forma de entrada:.
        /// </summary>
        internal static string boletagem_grid1_popup2_opcoes1 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_opcoes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Leitor Óptico.
        /// </summary>
        internal static string boletagem_grid1_popup2_opcoes2 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_opcoes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Digitação.
        /// </summary>
        internal static string boletagem_grid1_popup2_opcoes3 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_opcoes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Layout Boleto Bancário.
        /// </summary>
        internal static string boletagem_grid1_popup2_opcoes4 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_opcoes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Arrecadação.
        /// </summary>
        internal static string boletagem_grid1_popup2_opcoes5 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_opcoes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Bancário.
        /// </summary>
        internal static string boletagem_grid1_popup2_opcoes6 {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_opcoes6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nova Boletagem.
        /// </summary>
        internal static string boletagem_grid1_popup2_titulo {
            get {
                return ResourceManager.GetString("boletagem_grid1_popup2_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Auditoria.
        /// </summary>
        internal static string boletagem_grid2 {
            get {
                return ResourceManager.GetString("boletagem_grid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Rejeitar.
        /// </summary>
        internal static string boletagem_grid2_acao1 {
            get {
                return ResourceManager.GetString("boletagem_grid2_acao1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Conferir.
        /// </summary>
        internal static string boletagem_grid2_acao2 {
            get {
                return ResourceManager.GetString("boletagem_grid2_acao2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Área que disponibiliza as boletagens realizadas, o usuário poderá avaliar as boletas e realizar a auditoria..
        /// </summary>
        internal static string boletagem_grid2_guide {
            get {
                return ResourceManager.GetString("boletagem_grid2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Rejeitado.
        /// </summary>
        internal static string boletagem_grid2_status1 {
            get {
                return ResourceManager.GetString("boletagem_grid2_status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Conferido.
        /// </summary>
        internal static string boletagem_grid2_status2 {
            get {
                return ResourceManager.GetString("boletagem_grid2_status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Agenda.
        /// </summary>
        internal static string boletagem_grid3 {
            get {
                return ResourceManager.GetString("boletagem_grid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Criar Boletagem.
        /// </summary>
        internal static string boletagem_grid3_btn1 {
            get {
                return ResourceManager.GetString("boletagem_grid3_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Área onde serão exibidas as boletas futuras, ou seja, baseado na data de vencimento da verba o sistema irá programar os pagamentos futuros, é possível criar uma boletagem baseado nesta previsão.&lt;br/&gt;Para alterar os dados é possível clicando duas vezes na linha desejada, Para Inserir deve-se clicar no ícone + e preencher os campos. Para Excluir é necessário clicar no ícone da lixeira. Após qualquer dessas operações é necessário Salvar ou então Descartar..
        /// </summary>
        internal static string boletagem_grid3_guide {
            get {
                return ResourceManager.GetString("boletagem_grid3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modo de Exibição.
        /// </summary>
        internal static string boletagem_opcoes_1 {
            get {
                return ResourceManager.GetString("boletagem_opcoes_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data Entry: Acesso à área boletas, nessa área é possível visualizar as boletas criadas e ainda não auditadas, além de criar novas boletas manuais ou por débito em conta e também criar e associar novas Verbas.&lt;br/&gt;Auditoria: Área que disponibiliza as boletagens realizadas, o usuário poderá avaliar as boletas e realizar a auditoria. &lt;br/&gt;Agenda: Área onde serão exibidas as boletas futuras, ou seja, baseado na data de vencimento da verba o sistema irá programar os pagamentos futuros, é possível criar uma bolet [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string boletagem_opcoes_1_guide {
            get {
                return ResourceManager.GetString("boletagem_opcoes_1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data Entry.
        /// </summary>
        internal static string boletagem_opcoes_2 {
            get {
                return ResourceManager.GetString("boletagem_opcoes_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar o Mês e Ano da competência da boletagem, ou seja, o período que a boletagem foi realizada..
        /// </summary>
        internal static string boletagem_opcoes_2_lbl1_guide {
            get {
                return ResourceManager.GetString("boletagem_opcoes_2_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Auditoria.
        /// </summary>
        internal static string boletagem_opcoes_3 {
            get {
                return ResourceManager.GetString("boletagem_opcoes_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Competência.
        /// </summary>
        internal static string boletagem_opcoes_3_lbl1 {
            get {
                return ResourceManager.GetString("boletagem_opcoes_3_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar o período de Vencimento dos Boletos Futuros ainda não boletados..
        /// </summary>
        internal static string boletagem_opcoes_3_lbl1_guide {
            get {
                return ResourceManager.GetString("boletagem_opcoes_3_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar o período de Vencimento dos Boletos Futuros ainda não boletados..
        /// </summary>
        internal static string boletagem_opcoes_3_lbl2_guide {
            get {
                return ResourceManager.GetString("boletagem_opcoes_3_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Agenda.
        /// </summary>
        internal static string boletagem_opcoes_4 {
            get {
                return ResourceManager.GetString("boletagem_opcoes_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Boletagem.
        /// </summary>
        internal static string boletagem_titulo {
            get {
                return ResourceManager.GetString("boletagem_titulo", resourceCulture);
            }
        }
    }
}
