//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Formulas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Formulas() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Formulas", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/formulas/en-US.
        /// </summary>
        internal static string formulas_content_tutorial {
            get {
                return ResourceManager.GetString("formulas_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Identifier.
        /// </summary>
        internal static string formulas_grid_col1 {
            get {
                return ResourceManager.GetString("formulas_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        internal static string formulas_grid_col2 {
            get {
                return ResourceManager.GetString("formulas_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Participation (%).
        /// </summary>
        internal static string formulas_grid_col3 {
            get {
                return ResourceManager.GetString("formulas_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Days.
        /// </summary>
        internal static string formulas_grid_col4 {
            get {
                return ResourceManager.GetString("formulas_grid_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Indexer.
        /// </summary>
        internal static string formulas_grid_col5 {
            get {
                return ResourceManager.GetString("formulas_grid_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string formulas_lbl1 {
            get {
                return ResourceManager.GetString("formulas_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Base.
        /// </summary>
        internal static string formulas_lbl2 {
            get {
                return ResourceManager.GetString("formulas_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Formula.
        /// </summary>
        internal static string formulas_lbl3 {
            get {
                return ResourceManager.GetString("formulas_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Variables.
        /// </summary>
        internal static string formulas_lbl4 {
            get {
                return ResourceManager.GetString("formulas_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User action.
        /// </summary>
        internal static string formulas_lbl5 {
            get {
                return ResourceManager.GetString("formulas_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select Entity.
        /// </summary>
        internal static string formulas_lbl6 {
            get {
                return ResourceManager.GetString("formulas_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the Formula.
        /// </summary>
        internal static string formulas_lbl7 {
            get {
                return ResourceManager.GetString("formulas_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User action.
        /// </summary>
        internal static string formulas_quickguide_acao {
            get {
                return ResourceManager.GetString("formulas_quickguide_acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the basis for calculating the adjustment formula..
        /// </summary>
        internal static string formulas_quickguide_base {
            get {
                return ResourceManager.GetString("formulas_quickguide_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Field where the readjustment formula is written, the information is always based on the variables filled in the table below..
        /// </summary>
        internal static string formulas_quickguide_formula {
            get {
                return ResourceManager.GetString("formulas_quickguide_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adjustment formulas are the calculation basis used by the system to make the correct adjustment in the contract installments..
        /// </summary>
        internal static string formulas_quickguide_ini {
            get {
                return ResourceManager.GetString("formulas_quickguide_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name given to the Adjustment Formula, information that will be displayed in the registration of contracts..
        /// </summary>
        internal static string formulas_quickguide_nome {
            get {
                return ResourceManager.GetString("formulas_quickguide_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the Formula you want to view Formula details and management for..
        /// </summary>
        internal static string formulas_quickguide_pesquisa {
            get {
                return ResourceManager.GetString("formulas_quickguide_pesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a To perform a test on the Readjustment Formula, it is necessary to fill in some essential fields. Dates must be filled in according to the calculation formula, example: &lt;br/&gt; Formula (BASE / EVENT), Base Date and Event Date must be filled..
        /// </summary>
        internal static string formulas_quickguide_teste {
            get {
                return ResourceManager.GetString("formulas_quickguide_teste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adjustment formulas are the calculation basis used by the system to make the correct adjustment in the contract installments..
        /// </summary>
        internal static string formulas_quickguide_titulo {
            get {
                return ResourceManager.GetString("formulas_quickguide_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a The creation of variables is mandatory for the system to be able to perform the calculations correctly, for this the variable names must be the same as the names used in the Formula field above. To insert, click on the + icon and fill in the fields. To delete it is necessary to click on the trash can icon. After any of these operations it is necessary to Save or Discard..
        /// </summary>
        internal static string formulas_quickguide_variaveis {
            get {
                return ResourceManager.GetString("formulas_quickguide_variaveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Test.
        /// </summary>
        internal static string formulas_teste_btn {
            get {
                return ResourceManager.GetString("formulas_teste_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Base Date.
        /// </summary>
        internal static string formulas_teste_lbl1 {
            get {
                return ResourceManager.GetString("formulas_teste_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Event Date.
        /// </summary>
        internal static string formulas_teste_lbl2 {
            get {
                return ResourceManager.GetString("formulas_teste_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Payment Date.
        /// </summary>
        internal static string formulas_teste_lbl3 {
            get {
                return ResourceManager.GetString("formulas_teste_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Result.
        /// </summary>
        internal static string formulas_teste_lbl4 {
            get {
                return ResourceManager.GetString("formulas_teste_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Testing Formula.
        /// </summary>
        internal static string formulas_teste_titulo {
            get {
                return ResourceManager.GetString("formulas_teste_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adjustment Formulas.
        /// </summary>
        internal static string formulas_titulo_pag {
            get {
                return ResourceManager.GetString("formulas_titulo_pag", resourceCulture);
            }
        }
    }
}
