//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNesta_IRFS_16.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNesta_IRFS_16.App_GlobalResources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        public static string btn_alterar {
            get {
                return ResourceManager.GetString("btn_alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When clicking on the CHANGE button, the system enables the registration fields to edit the selected record. Follow the instructions contained in the Quick Guide to complete the content of each available field. By clicking on the OK button, the system validates the data entry and displays inconsistencies if found in a separate window. If there are no inconsistencies, the system updates the record in the database. By clicking on the CANCEL button the system discards all modifications and returns to the query  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string btn_alterar_qg {
            get {
                return ResourceManager.GetString("btn_alterar_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        public static string btn_cancelar {
            get {
                return ResourceManager.GetString("btn_cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When you click on the CANCEL button, the system discards all editions and returns to the query and navigation mode..
        /// </summary>
        public static string btn_cancelar_qg {
            get {
                return ResourceManager.GetString("btn_cancelar_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When you click on the CANCEL button, the system discards all bookings and returns to the query and navigation mode..
        /// </summary>
        public static string btn_cancelar2_qg {
            get {
                return ResourceManager.GetString("btn_cancelar2_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        public static string btn_consultar {
            get {
                return ResourceManager.GetString("btn_consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        public static string btn_excluir {
            get {
                return ResourceManager.GetString("btn_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When you click the DELETE button, the system marks the record selected for deletion. By clicking on the OK button, the system checks if there are any dependencies linked to the record marked for deletion and presents integrity violations if found in a separate window. If there are no dependencies, the system deletes the records from the database. When clicking on the CANCEL button the system discards the marking and returns to the query and navigation mode..
        /// </summary>
        public static string btn_excluir_qg {
            get {
                return ResourceManager.GetString("btn_excluir_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When clicking on the DELETE button, the system enables the grid to select the records to be deleted from the database. By clicking on the OK button, the system checks if there are any dependencies linked to the record marked for deletion and presents integrity violations if found in a separate window. If there are no dependencies, the system deletes the records from the database. When you click on the CANCEL button the system discards all bookings and returns to the query and navigation mode..
        /// </summary>
        public static string btn_excluir2_qg {
            get {
                return ResourceManager.GetString("btn_excluir2_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        public static string btn_fechar {
            get {
                return ResourceManager.GetString("btn_fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        public static string btn_grid_batch_cancel {
            get {
                return ResourceManager.GetString("btn_grid_batch_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deleted Values.
        /// </summary>
        public static string btn_grid_batch_deletevalues {
            get {
                return ResourceManager.GetString("btn_grid_batch_deletevalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hide Values.
        /// </summary>
        public static string btn_grid_batch_hide {
            get {
                return ResourceManager.GetString("btn_grid_batch_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Values.
        /// </summary>
        public static string btn_grid_batch_insertvalues {
            get {
                return ResourceManager.GetString("btn_grid_batch_insertvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preview.
        /// </summary>
        public static string btn_grid_batch_preview {
            get {
                return ResourceManager.GetString("btn_grid_batch_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        public static string btn_grid_batch_save {
            get {
                return ResourceManager.GetString("btn_grid_batch_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updated Values.
        /// </summary>
        public static string btn_grid_batch_updatevalues {
            get {
                return ResourceManager.GetString("btn_grid_batch_updatevalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Historic.
        /// </summary>
        public static string btn_historico {
            get {
                return ResourceManager.GetString("btn_historico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        public static string btn_inserir {
            get {
                return ResourceManager.GetString("btn_inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When clicking on the CREATE button, the system enables the registration fields to edit a new record. Follow the instructions contained in the Quick Guide to complete the content of each available field. By clicking on the OK button, the system validates the data entry and displays inconsistencies if found in a separate window. If there are no inconsistencies, the system inserts a new record in the database. By clicking on the CANCEL button the system discards all modifications and returns to the query and n [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string btn_inserir_qg {
            get {
                return ResourceManager.GetString("btn_inserir_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When clicking on the CREATE button, the system enables the registration fields in the grid to edit a new record. Follow the instructions contained in the Quick Guide to complete the content of each available field. By clicking on the SAVE button, the system validates the data entry and displays inconsistencies if found in a separate window. If there are no inconsistencies, the system inserts a new record in the database. By clicking on the DISCARD button the system discards all modifications and returns to  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string btn_inserir2_qg {
            get {
                return ResourceManager.GetString("btn_inserir2_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Integrate.
        /// </summary>
        public static string btn_integrar {
            get {
                return ResourceManager.GetString("btn_integrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a By clicking on the OK button, if in Inclusion or Change mode, the system validates the data entry and displays inconsistencies if found in a separate window. If there are no inconsistencies, the system inserts / updates the record in the database. If in Exclusion mode, the system checks if there are dependencies linked to the record and presents integrity violations if found in a separate window. In the absence of dependencies, the system deletes the record from the database..
        /// </summary>
        public static string btn_ok_qg {
            get {
                return ResourceManager.GetString("btn_ok_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a By clicking on the OK button, if in Inclusion or Change mode, the system validates the data entry and displays inconsistencies if found in a separate window. If there are no inconsistencies, the system inserts / updates the record in the database. If in Exclusion mode, the system checks if there are dependencies linked to the record and presents integrity violations if found in a separate window. In the absence of dependencies, the system deletes the record from the database..
        /// </summary>
        public static string btn_ok2_qg {
            get {
                return ResourceManager.GetString("btn_ok2_qg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Process.
        /// </summary>
        public static string btn_processar {
            get {
                return ResourceManager.GetString("btn_processar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Read More.
        /// </summary>
        public static string btn_readmore {
            get {
                return ResourceManager.GetString("btn_readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Duplicate.
        /// </summary>
        public static string btn_replicar {
            get {
                return ResourceManager.GetString("btn_replicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select.
        /// </summary>
        public static string btn_selecionar {
            get {
                return ResourceManager.GetString("btn_selecionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        public static string btn_selecione_loja_fechar {
            get {
                return ResourceManager.GetString("btn_selecione_loja_fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clean.
        /// </summary>
        public static string btn_selecione_loja_limpar {
            get {
                return ResourceManager.GetString("btn_selecione_loja_limpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select.
        /// </summary>
        public static string btn_selecione_loja_selecione {
            get {
                return ResourceManager.GetString("btn_selecione_loja_selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contract Registration.
        /// </summary>
        public static string btn4_1 {
            get {
                return ResourceManager.GetString("btn4.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lump Sum.
        /// </summary>
        public static string btn4_2 {
            get {
                return ResourceManager.GetString("btn4.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Date.
        /// </summary>
        public static string feriado_grid_col1 {
            get {
                return ResourceManager.GetString("feriado_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Holiday.
        /// </summary>
        public static string feriado_grid_col2 {
            get {
                return ResourceManager.GetString("feriado_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Country.
        /// </summary>
        public static string feriado_grid_col3 {
            get {
                return ResourceManager.GetString("feriado_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select Country:.
        /// </summary>
        public static string feriado_right_lbl1 {
            get {
                return ResourceManager.GetString("feriado_right_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Holidays.
        /// </summary>
        public static string feriado_tituloPag {
            get {
                return ResourceManager.GetString("feriado_tituloPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Supplier.
        /// </summary>
        public static string footer_link1 {
            get {
                return ResourceManager.GetString("footer_link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Documents.
        /// </summary>
        public static string footer_link10 {
            get {
                return ResourceManager.GetString("footer_link10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Cloud OCR Tools.
        /// </summary>
        public static string footer_link11 {
            get {
                return ResourceManager.GetString("footer_link11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parameterization of OCR Layouts.
        /// </summary>
        public static string footer_link11_1 {
            get {
                return ResourceManager.GetString("footer_link11.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tracking OCR Readings.
        /// </summary>
        public static string footer_link11_2 {
            get {
                return ResourceManager.GetString("footer_link11.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Monitoring.
        /// </summary>
        public static string footer_link12 {
            get {
                return ResourceManager.GetString("footer_link12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Funds.
        /// </summary>
        public static string footer_link13 {
            get {
                return ResourceManager.GetString("footer_link13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Book.
        /// </summary>
        public static string footer_link14 {
            get {
                return ResourceManager.GetString("footer_link14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Uploader.
        /// </summary>
        public static string footer_link15 {
            get {
                return ResourceManager.GetString("footer_link15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Appendix 1.
        /// </summary>
        public static string footer_link16 {
            get {
                return ResourceManager.GetString("footer_link16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Accounting Class.
        /// </summary>
        public static string footer_link2 {
            get {
                return ResourceManager.GetString("footer_link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Portfolio.
        /// </summary>
        public static string footer_link3 {
            get {
                return ResourceManager.GetString("footer_link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Formula.
        /// </summary>
        public static string footer_link4 {
            get {
                return ResourceManager.GetString("footer_link4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Indexers.
        /// </summary>
        public static string footer_link5 {
            get {
                return ResourceManager.GetString("footer_link5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + ETTJ Curve.
        /// </summary>
        public static string footer_link6 {
            get {
                return ResourceManager.GetString("footer_link6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Product.
        /// </summary>
        public static string footer_link7 {
            get {
                return ResourceManager.GetString("footer_link7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Payment.
        /// </summary>
        public static string footer_link8 {
            get {
                return ResourceManager.GetString("footer_link8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a + Chart of Accounts.
        /// </summary>
        public static string footer_link9 {
            get {
                return ResourceManager.GetString("footer_link9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Action.
        /// </summary>
        public static string footer_titulo {
            get {
                return ResourceManager.GetString("footer_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entity.
        /// </summary>
        public static string geral_selecione_loja_header {
            get {
                return ResourceManager.GetString("geral_selecione_loja_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To change the data it is possible to double-click on the desired line. To insert, click on the + icon and fill in the fields. To delete it is necessary to click on the trash can icon. After any of these operations it is necessary to Save or Discard..
        /// </summary>
        public static string guide_grid_edit {
            get {
                return ResourceManager.GetString("guide_grid_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a In use since.
        /// </summary>
        public static string header_desde {
            get {
                return ResourceManager.GetString("header_desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IFRS.16.
        /// </summary>
        public static string header_nome_aplicacao {
            get {
                return ResourceManager.GetString("header_nome_aplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Real estate system to comply with IFRS 16..
        /// </summary>
        public static string header_subtitulo {
            get {
                return ResourceManager.GetString("header_subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nesta cloud suites.
        /// </summary>
        public static string header_titulo {
            get {
                return ResourceManager.GetString("header_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nesta Cloud.
        /// </summary>
        public static string header_top1 {
            get {
                return ResourceManager.GetString("header_top1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expert System for Financial Management.
        /// </summary>
        public static string header_top2 {
            get {
                return ResourceManager.GetString("header_top2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hi.
        /// </summary>
        public static string inicial_card_1_texto1 {
            get {
                return ResourceManager.GetString("inicial_card_1_texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a , welcome!.
        /// </summary>
        public static string inicial_card_1_texto2 {
            get {
                return ResourceManager.GetString("inicial_card_1_texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consult the activity and pending information boards!.
        /// </summary>
        public static string inicial_card_1_texto3 {
            get {
                return ResourceManager.GetString("inicial_card_1_texto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opening of Works.
        /// </summary>
        public static string inicial_card_1_titulo {
            get {
                return ResourceManager.GetString("inicial_card_1_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        public static string inicial_card_2_texto1 {
            get {
                return ResourceManager.GetString("inicial_card_2_texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Active.
        /// </summary>
        public static string inicial_card_2_texto2 {
            get {
                return ResourceManager.GetString("inicial_card_2_texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closed.
        /// </summary>
        public static string inicial_card_2_texto3 {
            get {
                return ResourceManager.GetString("inicial_card_2_texto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expire 90 days.
        /// </summary>
        public static string inicial_card_2_texto4 {
            get {
                return ResourceManager.GetString("inicial_card_2_texto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Suspend.
        /// </summary>
        public static string inicial_card_2_texto5 {
            get {
                return ResourceManager.GetString("inicial_card_2_texto5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Judiciary.
        /// </summary>
        public static string inicial_card_2_texto6 {
            get {
                return ResourceManager.GetString("inicial_card_2_texto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contract Administration.
        /// </summary>
        public static string inicial_card_2_titulo {
            get {
                return ResourceManager.GetString("inicial_card_2_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Documents.
        /// </summary>
        public static string inicial_card_3_titulo {
            get {
                return ResourceManager.GetString("inicial_card_3_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Appendices.
        /// </summary>
        public static string inicial_card_4_titulo {
            get {
                return ResourceManager.GetString("inicial_card_4_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Currency Exchange.
        /// </summary>
        public static string inicial_card_5_titulo {
            get {
                return ResourceManager.GetString("inicial_card_5_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elaboration.
        /// </summary>
        public static string inicial_card_6_texto1 {
            get {
                return ResourceManager.GetString("inicial_card_6_texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Check.
        /// </summary>
        public static string inicial_card_6_texto2 {
            get {
                return ResourceManager.GetString("inicial_card_6_texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Approval.
        /// </summary>
        public static string inicial_card_6_texto3 {
            get {
                return ResourceManager.GetString("inicial_card_6_texto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Signature.
        /// </summary>
        public static string inicial_card_6_texto4 {
            get {
                return ResourceManager.GetString("inicial_card_6_texto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register.
        /// </summary>
        public static string inicial_card_6_texto5 {
            get {
                return ResourceManager.GetString("inicial_card_6_texto5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agreed.
        /// </summary>
        public static string inicial_card_6_texto6 {
            get {
                return ResourceManager.GetString("inicial_card_6_texto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contract Request.
        /// </summary>
        public static string inicial_card_6_titulo {
            get {
                return ResourceManager.GetString("inicial_card_6_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pending.
        /// </summary>
        public static string inicial_card_7_texto1 {
            get {
                return ResourceManager.GetString("inicial_card_7_texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing.
        /// </summary>
        public static string inicial_card_7_texto2 {
            get {
                return ResourceManager.GetString("inicial_card_7_texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updates.
        /// </summary>
        public static string inicial_card_7_texto3 {
            get {
                return ResourceManager.GetString("inicial_card_7_texto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quotation.
        /// </summary>
        public static string inicial_card_7_texto4 {
            get {
                return ResourceManager.GetString("inicial_card_7_texto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application for the management of contracts reached by IFRS 16, with resources for:.
        /// </summary>
        public static string inicial_guide_texto1 {
            get {
                return ResourceManager.GetString("inicial_guide_texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello, in your first access we strongly recommend that you consult the Tutorial IFRS 16..
        /// </summary>
        public static string inicial_guide_texto11 {
            get {
                return ResourceManager.GetString("inicial_guide_texto11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .Registration.
        /// </summary>
        public static string inicial_guide_texto2 {
            get {
                return ResourceManager.GetString("inicial_guide_texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a We have prepared a website with guidelines to help start using it..
        /// </summary>
        public static string inicial_guide_texto21 {
            get {
                return ResourceManager.GetString("inicial_guide_texto21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .Additions.
        /// </summary>
        public static string inicial_guide_texto3 {
            get {
                return ResourceManager.GetString("inicial_guide_texto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Access: @ webnestaifrs16..
        /// </summary>
        public static string inicial_guide_texto31 {
            get {
                return ResourceManager.GetString("inicial_guide_texto31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .Movements.
        /// </summary>
        public static string inicial_guide_texto4 {
            get {
                return ResourceManager.GetString("inicial_guide_texto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a #.
        /// </summary>
        public static string inicial_guide_texto41 {
            get {
                return ResourceManager.GetString("inicial_guide_texto41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .Accounts.
        /// </summary>
        public static string inicial_guide_texto5 {
            get {
                return ResourceManager.GetString("inicial_guide_texto5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .Budget.
        /// </summary>
        public static string inicial_guide_texto6 {
            get {
                return ResourceManager.GetString("inicial_guide_texto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .Results analysis.
        /// </summary>
        public static string inicial_guide_texto7 {
            get {
                return ResourceManager.GetString("inicial_guide_texto7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Process Pending.
        /// </summary>
        public static string interface_right_titulo {
            get {
                return ResourceManager.GetString("interface_right_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pending Integrations - Contract Creation.
        /// </summary>
        public static string interface_titulo1 {
            get {
                return ResourceManager.GetString("interface_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Duplicate record.
        /// </summary>
        public static string lbl_grid_batch_duplicated {
            get {
                return ResourceManager.GetString("lbl_grid_batch_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Since:.
        /// </summary>
        public static string login_date {
            get {
                return ResourceManager.GetString("login_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current Language:.
        /// </summary>
        public static string login_language {
            get {
                return ResourceManager.GetString("login_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User Logged:.
        /// </summary>
        public static string login_user {
            get {
                return ResourceManager.GetString("login_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home Page.
        /// </summary>
        public static string menu_botao1 {
            get {
                return ResourceManager.GetString("menu_botao1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About Nesta.
        /// </summary>
        public static string menu_botao10 {
            get {
                return ResourceManager.GetString("menu_botao10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logout.
        /// </summary>
        public static string menu_botao11 {
            get {
                return ResourceManager.GetString("menu_botao11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agreement Request.
        /// </summary>
        public static string menu_botao2 {
            get {
                return ResourceManager.GetString("menu_botao2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Real Estate.
        /// </summary>
        public static string menu_botao3 {
            get {
                return ResourceManager.GetString("menu_botao3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contract Registration.
        /// </summary>
        public static string menu_botao4 {
            get {
                return ResourceManager.GetString("menu_botao4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payments Flow.
        /// </summary>
        public static string menu_botao5 {
            get {
                return ResourceManager.GetString("menu_botao5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IFRS Cash Flow.
        /// </summary>
        public static string menu_botao6 {
            get {
                return ResourceManager.GetString("menu_botao6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Workflow.
        /// </summary>
        public static string menu_botao7 {
            get {
                return ResourceManager.GetString("menu_botao7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Facilities.
        /// </summary>
        public static string menu_botao8 {
            get {
                return ResourceManager.GetString("menu_botao8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User Profile.
        /// </summary>
        public static string menu_botao9 {
            get {
                return ResourceManager.GetString("menu_botao9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logout.
        /// </summary>
        public static string menu_botaoSair {
            get {
                return ResourceManager.GetString("menu_botaoSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About.
        /// </summary>
        public static string menu_botaoSobre {
            get {
                return ResourceManager.GetString("menu_botaoSobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current Language:.
        /// </summary>
        public static string menu_idioma {
            get {
                return ResourceManager.GetString("menu_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logged as:.
        /// </summary>
        public static string menu_usuario {
            get {
                return ResourceManager.GetString("menu_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password expire date:.
        /// </summary>
        public static string menu_validade {
            get {
                return ResourceManager.GetString("menu_validade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exception:.
        /// </summary>
        public static string msg_alert_exception {
            get {
                return ResourceManager.GetString("msg_alert_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your action was successfull completed..
        /// </summary>
        public static string msg_alert_success {
            get {
                return ResourceManager.GetString("msg_alert_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Not allowed to delete item in use..
        /// </summary>
        public static string MsgExc_delete_item_using {
            get {
                return ResourceManager.GetString("MsgExc_delete_item_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alert Message:.
        /// </summary>
        public static string popup_exception {
            get {
                return ResourceManager.GetString("popup_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To use the Multi-language option, it is necessary to open a ticket to enable the feature..
        /// </summary>
        public static string popup_language_choose {
            get {
                return ResourceManager.GetString("popup_language_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        public static string popup_session_btnNo {
            get {
                return ResourceManager.GetString("popup_session_btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        public static string popup_session_btnYes {
            get {
                return ResourceManager.GetString("popup_session_btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your current session will expire in.
        /// </summary>
        public static string popup_session_texto1 {
            get {
                return ResourceManager.GetString("popup_session_texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a seconds..
        /// </summary>
        public static string popup_session_texto2 {
            get {
                return ResourceManager.GetString("popup_session_texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to reset it?.
        /// </summary>
        public static string popup_session_texto3 {
            get {
                return ResourceManager.GetString("popup_session_texto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Session Expiring..
        /// </summary>
        public static string popup_session_titulo {
            get {
                return ResourceManager.GetString("popup_session_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mouse over some systems field where the information related will be shown in this board..
        /// </summary>
        public static string quickguide_inicial {
            get {
                return ResourceManager.GetString("quickguide_inicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a is required..
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use the filters to manipulate the sample data. Click on the column title to sort the data in ascending ↑ or descending ↓ order. Double click on the grid line to load the form with all the properties of the selected contract..
        /// </summary>
        public static string sel_contrato_guide {
            get {
                return ResourceManager.GetString("sel_contrato_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select the desired property to load the data.
        /// </summary>
        public static string sel_imovel_guide {
            get {
                return ResourceManager.GetString("sel_imovel_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose the structure of the economic GROUP, the COMPANY or the branch you intend to subordinate to the contract you are going to register..
        /// </summary>
        public static string sel_loja_guide {
            get {
                return ResourceManager.GetString("sel_loja_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Click to see all tips about this field..
        /// </summary>
        public static string tip_guide_label {
            get {
                return ResourceManager.GetString("tip_guide_label", resourceCulture);
            }
        }
    }
}
