//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Indice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Indice() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Indice", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Rate.
        /// </summary>
        internal static string indexador_combo1_item1 {
            get {
                return ResourceManager.GetString("indexador_combo1_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Index.
        /// </summary>
        internal static string indexador_combo1_item2 {
            get {
                return ResourceManager.GetString("indexador_combo1_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Currency Parity.
        /// </summary>
        internal static string indexador_combo1_item3 {
            get {
                return ResourceManager.GetString("indexador_combo1_item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Future Stock Exchange.
        /// </summary>
        internal static string indexador_combo1_item4 {
            get {
                return ResourceManager.GetString("indexador_combo1_item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a PUT Stock Exchange.
        /// </summary>
        internal static string indexador_combo1_item5 {
            get {
                return ResourceManager.GetString("indexador_combo1_item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a CALL Stock Exchange.
        /// </summary>
        internal static string indexador_combo1_item6 {
            get {
                return ResourceManager.GetString("indexador_combo1_item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Daily.
        /// </summary>
        internal static string indexador_combo2_item1 {
            get {
                return ResourceManager.GetString("indexador_combo2_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Monthly.
        /// </summary>
        internal static string indexador_combo2_item2 {
            get {
                return ResourceManager.GetString("indexador_combo2_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Date.
        /// </summary>
        internal static string indexador_grid_col1 {
            get {
                return ResourceManager.GetString("indexador_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Quotation.
        /// </summary>
        internal static string indexador_grid_col2 {
            get {
                return ResourceManager.GetString("indexador_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Provisional.
        /// </summary>
        internal static string indexador_grid_col3 {
            get {
                return ResourceManager.GetString("indexador_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string indexador_lbl1 {
            get {
                return ResourceManager.GetString("indexador_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Initials.
        /// </summary>
        internal static string indexador_lbl2 {
            get {
                return ResourceManager.GetString("indexador_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Label.
        /// </summary>
        internal static string indexador_lbl3 {
            get {
                return ResourceManager.GetString("indexador_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        internal static string indexador_lbl4 {
            get {
                return ResourceManager.GetString("indexador_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Frequency.
        /// </summary>
        internal static string indexador_lbl5 {
            get {
                return ResourceManager.GetString("indexador_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string indexador_lbl6 {
            get {
                return ResourceManager.GetString("indexador_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Direct.
        /// </summary>
        internal static string indexador_lbl6_1 {
            get {
                return ResourceManager.GetString("indexador_lbl6.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accumulated.
        /// </summary>
        internal static string indexador_lbl6_2 {
            get {
                return ResourceManager.GetString("indexador_lbl6.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Feeder Number.
        /// </summary>
        internal static string indexador_lbl7 {
            get {
                return ResourceManager.GetString("indexador_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Model.
        /// </summary>
        internal static string indexador_modelo {
            get {
                return ResourceManager.GetString("indexador_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Action.
        /// </summary>
        internal static string indexador_right_titulo1 {
            get {
                return ResourceManager.GetString("indexador_right_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select Entity.
        /// </summary>
        internal static string indexador_right_titulo2 {
            get {
                return ResourceManager.GetString("indexador_right_titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        internal static string indexador_right_titulo3 {
            get {
                return ResourceManager.GetString("indexador_right_titulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Details.
        /// </summary>
        internal static string indexador_titulo1 {
            get {
                return ResourceManager.GetString("indexador_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Quotation.
        /// </summary>
        internal static string indexador_titulo2 {
            get {
                return ResourceManager.GetString("indexador_titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Future.
        /// </summary>
        internal static string indexador_titulo2_1 {
            get {
                return ResourceManager.GetString("indexador_titulo2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Indexers.
        /// </summary>
        internal static string indexador_tituloPag {
            get {
                return ResourceManager.GetString("indexador_tituloPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Indexers and Currencies are necessary for contracts to be updated correctly according to the contractual guidelines, for this to happen correctly, indexers and currencies must be properly registered and updated..
        /// </summary>
        internal static string indice_acao {
            get {
                return ResourceManager.GetString("indice_acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/indexadores/en-US.
        /// </summary>
        internal static string indice_content_tutorial {
            get {
                return ResourceManager.GetString("indice_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Up-to-date quotes for the Indexer or Currency searched, To change the data, you can double-click on the desired line. To insert, click on the + icon and fill in the fields. To delete it is necessary to click on the trash can icon. After any of these operations it is necessary to Save or Discard..
        /// </summary>
        internal static string indice_cotacao {
            get {
                return ResourceManager.GetString("indice_cotacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name given to the Index to facilitate localization and management..
        /// </summary>
        internal static string indice_descrição {
            get {
                return ResourceManager.GetString("indice_descrição", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Details.
        /// </summary>
        internal static string indice_detalhes {
            get {
                return ResourceManager.GetString("indice_detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select whether the frequency of quote publication happens daily or monthly..
        /// </summary>
        internal static string indice_freq {
            get {
                return ResourceManager.GetString("indice_freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type of Indexer registration &lt;br /&gt; Location: Indexer or Currency used exclusively by the Company where quotations and updates are the responsibility of the user. &lt;br /&gt; Global: Indexer or Global Currency where all companies use, the accounts and the management are the responsibility of Nesta..
        /// </summary>
        internal static string indice_modelo {
            get {
                return ResourceManager.GetString("indice_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the Indexer according to the selected Store to have access to detailed information..
        /// </summary>
        internal static string indice_pesquisa {
            get {
                return ResourceManager.GetString("indice_pesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Label used to identify the Indexer.
        /// </summary>
        internal static string indice_rotulo {
            get {
                return ResourceManager.GetString("indice_rotulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select.
        /// </summary>
        internal static string indice_selecione {
            get {
                return ResourceManager.GetString("indice_selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Acronym used to identify the Indexer.
        /// </summary>
        internal static string indice_sigla {
            get {
                return ResourceManager.GetString("indice_sigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the best option that fits the Indexer..
        /// </summary>
        internal static string indice_tipo {
            get {
                return ResourceManager.GetString("indice_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Indexers and Currencies are necessary for contracts to be updated correctly according to the contractual guidelines, for this to happen correctly, indexers and currencies must be properly registered and updated..
        /// </summary>
        internal static string indice_titulo {
            get {
                return ResourceManager.GetString("indice_titulo", resourceCulture);
            }
        }
    }
}
