//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Monitoramento {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Monitoramento() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Monitoramento", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/monitoramento/en-US.
        /// </summary>
        internal static string monitoramento_content_tutorial {
            get {
                return ResourceManager.GetString("monitoramento_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data Entry.
        /// </summary>
        internal static string monitoramento_grid1 {
            get {
                return ResourceManager.GetString("monitoramento_grid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exibição dos boletos agrupados para processamento e envio ao Contas a Pagar. &lt;br/&gt;Processar: Função que é habilitada quando algum registro é selecionado, a função irá processar o envio do registro ao contas a pagar e assim efetuar o pagamento.&lt;br/&gt;Notificar: Função de alerta aos responsáveis por aprovação do processamento dos devidos pagamentos..
        /// </summary>
        internal static string monitoramento_grid1_guide {
            get {
                return ResourceManager.GetString("monitoramento_grid1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Auditoria.
        /// </summary>
        internal static string monitoramento_grid2 {
            get {
                return ResourceManager.GetString("monitoramento_grid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exibição dos boletos pendente de aprovação para habilitar o registro para processamento do Contas a Pagar.&lt;br/&gt;Aprovar: Função é habilitada após os registros serem selecionados. Apenas é possível selecionar os registros caso o usuário seja um aprovador cadastrado..
        /// </summary>
        internal static string monitoramento_grid2_guide {
            get {
                return ResourceManager.GetString("monitoramento_grid2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string monitoramento_guide_ini {
            get {
                return ResourceManager.GetString("monitoramento_guide_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Intervalo em dias.
        /// </summary>
        internal static string monitoramento_lbl2 {
            get {
                return ResourceManager.GetString("monitoramento_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Intervalo em dias entre os períodos selecionados. O sistema irá calcular a Data Final conforme o valor informado e a Data Inicial selecionada..
        /// </summary>
        internal static string monitoramento_lbl2_guide {
            get {
                return ResourceManager.GetString("monitoramento_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data Inicial.
        /// </summary>
        internal static string monitoramento_lbl3 {
            get {
                return ResourceManager.GetString("monitoramento_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar primeira data de vencimento para consultar as boletas disponíveis.
        /// </summary>
        internal static string monitoramento_lbl3_guide {
            get {
                return ResourceManager.GetString("monitoramento_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data Final.
        /// </summary>
        internal static string monitoramento_lbl4 {
            get {
                return ResourceManager.GetString("monitoramento_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar última data de vencimento para consultar as boletas disponíveis.
        /// </summary>
        internal static string monitoramento_lbl4_guide {
            get {
                return ResourceManager.GetString("monitoramento_lbl4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Situação.
        /// </summary>
        internal static string monitoramento_lbl5 {
            get {
                return ResourceManager.GetString("monitoramento_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Conforme o período selecionado acima, é possível exibir apenas boletos já vencidos ou ainda a vencer..
        /// </summary>
        internal static string monitoramento_lbl5_guide {
            get {
                return ResourceManager.GetString("monitoramento_lbl5_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contas Pagar.
        /// </summary>
        internal static string monitoramento_right_btn1 {
            get {
                return ResourceManager.GetString("monitoramento_right_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Consultar Boletos auditados e disponíveis para que sejam enviados para o Contas a Pagar..
        /// </summary>
        internal static string monitoramento_right_btn1_guide {
            get {
                return ResourceManager.GetString("monitoramento_right_btn1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Aprovação.
        /// </summary>
        internal static string monitoramento_right_btn2 {
            get {
                return ResourceManager.GetString("monitoramento_right_btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Consultar Boletos pendentes de aprovação de valores, para que seja possível processar o devido pagamento..
        /// </summary>
        internal static string monitoramento_right_btn2_guide {
            get {
                return ResourceManager.GetString("monitoramento_right_btn2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vencido.
        /// </summary>
        internal static string monitoramento_right_combo1_item1 {
            get {
                return ResourceManager.GetString("monitoramento_right_combo1_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a a Vencer.
        /// </summary>
        internal static string monitoramento_right_combo1_item2 {
            get {
                return ResourceManager.GetString("monitoramento_right_combo1_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecione a Empresa.
        /// </summary>
        internal static string monitoramento_right_titulo2 {
            get {
                return ResourceManager.GetString("monitoramento_right_titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Monitoramento Diário de Boletas.
        /// </summary>
        internal static string monitoramento_tituloPag {
            get {
                return ResourceManager.GetString("monitoramento_tituloPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ações do usuário.
        /// </summary>
        internal static string monitoramento_tituloRight {
            get {
                return ResourceManager.GetString("monitoramento_tituloRight", resourceCulture);
            }
        }
    }
}
