//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RealEstate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RealEstate() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RealEstate", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Empresa.
        /// </summary>
        internal static string label_grp1_01 {
            get {
                return ResourceManager.GetString("label_grp1_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Escolha a estrutura do GRUPO econômico, da EMPRESA ou da FILIAL que você pretende subordinar o contrato que irá cadastrar.
        /// </summary>
        internal static string label_grp1_01_guide {
            get {
                return ResourceManager.GetString("label_grp1_01_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tipo Imóvel.
        /// </summary>
        internal static string label_grp1_02 {
            get {
                return ResourceManager.GetString("label_grp1_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Escolha o tipo de imóvel que se enquadra melhor.
        /// </summary>
        internal static string label_grp1_02_guide {
            get {
                return ResourceManager.GetString("label_grp1_02_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string label_grp1_03 {
            get {
                return ResourceManager.GetString("label_grp1_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informação que servirá como objeto de localização do imóvel.
        /// </summary>
        internal static string label_grp1_03_guide {
            get {
                return ResourceManager.GetString("label_grp1_03_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No. Contribuinte.
        /// </summary>
        internal static string label_grp1_04 {
            get {
                return ResourceManager.GetString("label_grp1_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informação relativa ao cadastro do imóvel na prefeitura correspondente.
        /// </summary>
        internal static string label_grp1_04_guide {
            get {
                return ResourceManager.GetString("label_grp1_04_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Endereço Completo.
        /// </summary>
        internal static string label_grp1_05 {
            get {
                return ResourceManager.GetString("label_grp1_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ao inserir o CEP o sistema irá preencher o campo Endereço Completo com as informações extraídas do Google Maps.
        /// </summary>
        internal static string label_grp1_05_guide {
            get {
                return ResourceManager.GetString("label_grp1_05_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vago.
        /// </summary>
        internal static string label_grp1_06 {
            get {
                return ResourceManager.GetString("label_grp1_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vago.
        /// </summary>
        internal static string label_grp1_06_guide {
            get {
                return ResourceManager.GetString("label_grp1_06_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a CEP.
        /// </summary>
        internal static string label_grp1_07 {
            get {
                return ResourceManager.GetString("label_grp1_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Endereço relativo ao CEP preenchido, caso seja necessário a correção poderá ser feita diretamente nesse campo..
        /// </summary>
        internal static string label_grp1_07_guide {
            get {
                return ResourceManager.GetString("label_grp1_07_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cod Logradouro.
        /// </summary>
        internal static string label_grp1_08 {
            get {
                return ResourceManager.GetString("label_grp1_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecione o tipo de Logradouro referente ao endereço do imóvel.
        /// </summary>
        internal static string label_grp1_08_guide {
            get {
                return ResourceManager.GetString("label_grp1_08_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ano Construção.
        /// </summary>
        internal static string label_grp1_09 {
            get {
                return ResourceManager.GetString("label_grp1_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ano de construção do imóvel referenciado.
        /// </summary>
        internal static string label_grp1_09_guide {
            get {
                return ResourceManager.GetString("label_grp1_09_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Situação Legal.
        /// </summary>
        internal static string label_grp1_10 {
            get {
                return ResourceManager.GetString("label_grp1_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Situação Legal que melhor se enquadre ao imóvel.
        /// </summary>
        internal static string label_grp1_10_guide {
            get {
                return ResourceManager.GetString("label_grp1_10_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No. Processo de Registro.
        /// </summary>
        internal static string label_grp1_11 {
            get {
                return ResourceManager.GetString("label_grp1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Número referente ao processo de registro do imóvel junto ao cartório.
        /// </summary>
        internal static string label_grp1_11_guide {
            get {
                return ResourceManager.GetString("label_grp1_11_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Testada Principal.
        /// </summary>
        internal static string label_grp1_12 {
            get {
                return ResourceManager.GetString("label_grp1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informação da largura do terreno do imóvel, caso seja em esquina deve-se somar a testada da frente (principal) e a testada lateral (secundária).
        /// </summary>
        internal static string label_grp1_12_guide {
            get {
                return ResourceManager.GetString("label_grp1_12_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Área do Terreno.
        /// </summary>
        internal static string label_grp1_13 {
            get {
                return ResourceManager.GetString("label_grp1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informação da área em metros quadrados do terreno do imóvel.
        /// </summary>
        internal static string label_grp1_13_guide {
            get {
                return ResourceManager.GetString("label_grp1_13_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Área Edificada.
        /// </summary>
        internal static string label_grp1_14 {
            get {
                return ResourceManager.GetString("label_grp1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informação da área total coberta do imóvel em metros quadrados.
        /// </summary>
        internal static string label_grp1_14_guide {
            get {
                return ResourceManager.GetString("label_grp1_14_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Área Comum.
        /// </summary>
        internal static string label_grp1_15 {
            get {
                return ResourceManager.GetString("label_grp1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informação em metros quadrados que compreende à área comum do imóvel.
        /// </summary>
        internal static string label_grp1_15_guide {
            get {
                return ResourceManager.GetString("label_grp1_15_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fração Ideal.
        /// </summary>
        internal static string label_grp1_16 {
            get {
                return ResourceManager.GetString("label_grp1_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Anote a fração ideal de terreno correspondente ao imóvel alugado.
        /// </summary>
        internal static string label_grp1_16_guide {
            get {
                return ResourceManager.GetString("label_grp1_16_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data do Registro.
        /// </summary>
        internal static string label_grp1_17 {
            get {
                return ResourceManager.GetString("label_grp1_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data em que o imóvel foi registrado em cartório.
        /// </summary>
        internal static string label_grp1_17_guide {
            get {
                return ResourceManager.GetString("label_grp1_17_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Valor Venal.
        /// </summary>
        internal static string label_grp1_18 {
            get {
                return ResourceManager.GetString("label_grp1_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Valor venal informado pela prefeitura que serve como base para cálculos de impostos e taxas.
        /// </summary>
        internal static string label_grp1_18_guide {
            get {
                return ResourceManager.GetString("label_grp1_18_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vago.
        /// </summary>
        internal static string label_grp1_19 {
            get {
                return ResourceManager.GetString("label_grp1_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vago.
        /// </summary>
        internal static string label_grp1_19_guide {
            get {
                return ResourceManager.GetString("label_grp1_19_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vago.
        /// </summary>
        internal static string label_grp1_20 {
            get {
                return ResourceManager.GetString("label_grp1_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vago.
        /// </summary>
        internal static string label_grp1_20_guide {
            get {
                return ResourceManager.GetString("label_grp1_20_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vistoria.
        /// </summary>
        internal static string label_grp2_01 {
            get {
                return ResourceManager.GetString("label_grp2_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data em que será realizada a vistoria de entrega do imóvel.
        /// </summary>
        internal static string label_grp2_01_guide {
            get {
                return ResourceManager.GetString("label_grp2_01_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Recebimento Chaves.
        /// </summary>
        internal static string label_grp2_02 {
            get {
                return ResourceManager.GetString("label_grp2_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data em que será realizado a entrega das chaves do locador para o locatário..
        /// </summary>
        internal static string label_grp2_02_guide {
            get {
                return ResourceManager.GetString("label_grp2_02_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Devolução Chaves.
        /// </summary>
        internal static string label_grp2_03 {
            get {
                return ResourceManager.GetString("label_grp2_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data em que é prevista a devolução das chaves do locatário para o locador..
        /// </summary>
        internal static string label_grp2_03_guide {
            get {
                return ResourceManager.GetString("label_grp2_03_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inauguração.
        /// </summary>
        internal static string label_grp2_04 {
            get {
                return ResourceManager.GetString("label_grp2_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data em que é prevista a inauguração do imóvel.
        /// </summary>
        internal static string label_grp2_04_guide {
            get {
                return ResourceManager.GetString("label_grp2_04_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/imoveis/en-US.
        /// </summary>
        internal static string realestate_content_tutorial {
            get {
                return ResourceManager.GetString("realestate_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Dados Cadastrais.
        /// </summary>
        internal static string titulo_grp1 {
            get {
                return ResourceManager.GetString("titulo_grp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Dados Cadastrais.
        /// </summary>
        internal static string titulo_grp1_guide {
            get {
                return ResourceManager.GetString("titulo_grp1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Posse do Imóvel.
        /// </summary>
        internal static string titulo_grp2 {
            get {
                return ResourceManager.GetString("titulo_grp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Posse do Imóvel.
        /// </summary>
        internal static string titulo_grp2_guide {
            get {
                return ResourceManager.GetString("titulo_grp2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Propriedade do Imóvel.
        /// </summary>
        internal static string titulo_grp3 {
            get {
                return ResourceManager.GetString("titulo_grp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Área onde contém os dados dos responsáveis pelo imóvel e suas formas de contato direta, é possível enviar mensagens por e-mail ou por WhatsApp.
        /// </summary>
        internal static string titulo_grp3_guide {
            get {
                return ResourceManager.GetString("titulo_grp3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Impostos, Taxas e Seguro.
        /// </summary>
        internal static string titulo_grp4 {
            get {
                return ResourceManager.GetString("titulo_grp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Área para registro das cobranças extras contratado, como IPTU, Seguros e outras Taxas. A inclusão de algumas taxas irá gerar um registro de acompanhado no WorkFlow de Administração de Contrato.
        /// </summary>
        internal static string titulo_grp4_guide {
            get {
                return ResourceManager.GetString("titulo_grp4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Documentos e Arquivos.
        /// </summary>
        internal static string titulo_grp5 {
            get {
                return ResourceManager.GetString("titulo_grp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Espaço de memória para armazenar todos os documentos e arquivos necessários relacionados ao imóvel, inclusive os registros de comunicação entre locatário e locador..
        /// </summary>
        internal static string titulo_grp5_guide {
            get {
                return ResourceManager.GetString("titulo_grp5_guide", resourceCulture);
            }
        }
    }
}
