//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setup() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Setup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/query/en-US.
        /// </summary>
        internal static string relatorio_content_tutorial {
            get {
                return ResourceManager.GetString("relatorio_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Texto para início sobre Relatório.
        /// </summary>
        internal static string relatorio_guide_ini {
            get {
                return ResourceManager.GetString("relatorio_guide_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Report Name.
        /// </summary>
        internal static string relatorio_lbl1 {
            get {
                return ResourceManager.GetString("relatorio_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Texto sobre nome.
        /// </summary>
        internal static string relatorio_nome_guide {
            get {
                return ResourceManager.GetString("relatorio_nome_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Texto sobre query.
        /// </summary>
        internal static string relatorio_query_guide {
            get {
                return ResourceManager.GetString("relatorio_query_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Texto sobre tipo.
        /// </summary>
        internal static string relatorio_tipo_guide {
            get {
                return ResourceManager.GetString("relatorio_tipo_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/facilities/en-US.
        /// </summary>
        internal static string setup_content_tutorial {
            get {
                return ResourceManager.GetString("setup_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Reports: Menu where the advanced user will be able to create and manage the report documents of their use. &lt;br /&gt; Manage Users (Administrator Access): &lt;br /&gt; Registration: Management of system users. Password Creation, Deactivation and Reset. &lt;br /&gt; Approvers: Management of Accounts Payable approvers and their associated levels. &lt;br /&gt; Logged User: View of logged users and their last uses. &lt;br /&gt; Store Registration: Area intended for the creation of stores (Companies) and their affiliations, and the possibi [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string setup_guide {
            get {
                return ResourceManager.GetString("setup_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Reports.
        /// </summary>
        internal static string setup_menu1 {
            get {
                return ResourceManager.GetString("setup_menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Report Name.
        /// </summary>
        internal static string setup_menu1_col1 {
            get {
                return ResourceManager.GetString("setup_menu1_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type of Report.
        /// </summary>
        internal static string setup_menu1_col2 {
            get {
                return ResourceManager.GetString("setup_menu1_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Query.
        /// </summary>
        internal static string setup_menu1_col3 {
            get {
                return ResourceManager.GetString("setup_menu1_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Detail.
        /// </summary>
        internal static string setup_menu1_col3_btn {
            get {
                return ResourceManager.GetString("setup_menu1_col3-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Report Management.
        /// </summary>
        internal static string setup_menu1_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Actions.
        /// </summary>
        internal static string setup_menu1_lbl2 {
            get {
                return ResourceManager.GetString("setup_menu1_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Users Management.
        /// </summary>
        internal static string setup_menu2 {
            get {
                return ResourceManager.GetString("setup_menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Registration.
        /// </summary>
        internal static string setup_menu2_1 {
            get {
                return ResourceManager.GetString("setup_menu2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Profile.
        /// </summary>
        internal static string setup_menu2_1_col1 {
            get {
                return ResourceManager.GetString("setup_menu2-1_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string setup_menu2_1_col2 {
            get {
                return ResourceManager.GetString("setup_menu2-1_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        internal static string setup_menu2_1_col3 {
            get {
                return ResourceManager.GetString("setup_menu2-1_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Last Name.
        /// </summary>
        internal static string setup_menu2_1_col4 {
            get {
                return ResourceManager.GetString("setup_menu2-1_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Name.
        /// </summary>
        internal static string setup_menu2_1_col5 {
            get {
                return ResourceManager.GetString("setup_menu2-1_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a WhatsApp.
        /// </summary>
        internal static string setup_menu2_1_col6 {
            get {
                return ResourceManager.GetString("setup_menu2-1_col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string setup_menu2_1_col7 {
            get {
                return ResourceManager.GetString("setup_menu2-1_col7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Deactivate.
        /// </summary>
        internal static string setup_menu2_1_hint1 {
            get {
                return ResourceManager.GetString("setup_menu2-1_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Reset Password.
        /// </summary>
        internal static string setup_menu2_1_hint2 {
            get {
                return ResourceManager.GetString("setup_menu2-1_hint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Reactivate.
        /// </summary>
        internal static string setup_menu2_1_hint3 {
            get {
                return ResourceManager.GetString("setup_menu2-1_hint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Users Management - Registration.
        /// </summary>
        internal static string setup_menu2_1_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu2-1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Approvers.
        /// </summary>
        internal static string setup_menu2_2 {
            get {
                return ResourceManager.GetString("setup_menu2-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Level.
        /// </summary>
        internal static string setup_menu2_2_grid1_col1 {
            get {
                return ResourceManager.GetString("setup_menu2-2_grid1_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a UserName.
        /// </summary>
        internal static string setup_menu2_2_grid1_col2 {
            get {
                return ResourceManager.GetString("setup_menu2-2_grid1_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Associated Users.
        /// </summary>
        internal static string setup_menu2_2_grid1_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu2-2_grid1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Level.
        /// </summary>
        internal static string setup_menu2_2_grid2_col1 {
            get {
                return ResourceManager.GetString("setup_menu2-2_grid2_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Start value.
        /// </summary>
        internal static string setup_menu2_2_grid2_col2 {
            get {
                return ResourceManager.GetString("setup_menu2-2_grid2_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Final value.
        /// </summary>
        internal static string setup_menu2_2_grid2_col3 {
            get {
                return ResourceManager.GetString("setup_menu2-2_grid2_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Approval Profile.
        /// </summary>
        internal static string setup_menu2_2_grid2_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu2-2_grid2_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Users Management - Approvers.
        /// </summary>
        internal static string setup_menu2_2_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu2-2_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Users Logged.
        /// </summary>
        internal static string setup_menu2_3 {
            get {
                return ResourceManager.GetString("setup_menu2-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string setup_menu2_3_grid1_col1 {
            get {
                return ResourceManager.GetString("setup_menu2-3_grid1_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Last Name.
        /// </summary>
        internal static string setup_menu2_3_grid1_col2 {
            get {
                return ResourceManager.GetString("setup_menu2-3_grid1_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Name.
        /// </summary>
        internal static string setup_menu2_3_grid1_col3 {
            get {
                return ResourceManager.GetString("setup_menu2-3_grid1_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Last Activity.
        /// </summary>
        internal static string setup_menu2_3_grid1_col4 {
            get {
                return ResourceManager.GetString("setup_menu2-3_grid1_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Module.
        /// </summary>
        internal static string setup_menu2_3_grid1_col5 {
            get {
                return ResourceManager.GetString("setup_menu2-3_grid1_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string setup_menu2_3_grid1_col6 {
            get {
                return ResourceManager.GetString("setup_menu2-3_grid1_col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Users Logged.
        /// </summary>
        internal static string setup_menu2_3_grid1_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu2-3_grid1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Users Management - Users Logged.
        /// </summary>
        internal static string setup_menu2_3_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu2-3_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Entity.
        /// </summary>
        internal static string setup_menu3 {
            get {
                return ResourceManager.GetString("setup_menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Entity Settings.
        /// </summary>
        internal static string setup_menu3_1 {
            get {
                return ResourceManager.GetString("setup_menu3-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Financial Market.
        /// </summary>
        internal static string setup_menu3_2 {
            get {
                return ResourceManager.GetString("setup_menu3-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Associated User.
        /// </summary>
        internal static string setup_menu3_grid1_col1 {
            get {
                return ResourceManager.GetString("setup_menu3_grid1_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Available User.
        /// </summary>
        internal static string setup_menu3_grid2_col1 {
            get {
                return ResourceManager.GetString("setup_menu3_grid2_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Entity Settings.
        /// </summary>
        internal static string setup_menu3_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select if the company to register is Headquarters or Branch. &lt;br/&gt; Headquarters does not have any company superior to it &lt;br/&gt; Branch is necessary to select a company in the Group field to be associated.
        /// </summary>
        internal static string setup_menu3_lbl1_guide {
            get {
                return ResourceManager.GetString("setup_menu3_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        internal static string setup_menu3_lbl2 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the Group to which the company is affiliated, if applicable..
        /// </summary>
        internal static string setup_menu3_lbl2_guide {
            get {
                return ResourceManager.GetString("setup_menu3_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Headquarters.
        /// </summary>
        internal static string setup_menu3_lbl2_opt1 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl2-opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Branch.
        /// </summary>
        internal static string setup_menu3_lbl2_opt2 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl2-opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Group.
        /// </summary>
        internal static string setup_menu3_lbl3 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company name related to the company.
        /// </summary>
        internal static string setup_menu3_lbl3_guide {
            get {
                return ResourceManager.GetString("setup_menu3_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company name.
        /// </summary>
        internal static string setup_menu3_lbl4 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Short name referring to the corporate name.
        /// </summary>
        internal static string setup_menu3_lbl4_guide {
            get {
                return ResourceManager.GetString("setup_menu3_lbl4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Short name.
        /// </summary>
        internal static string setup_menu3_lbl5 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company registration code, in Brazil the CNPJ code is used..
        /// </summary>
        internal static string setup_menu3_lbl5_guide {
            get {
                return ResourceManager.GetString("setup_menu3_lbl5_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Code.
        /// </summary>
        internal static string setup_menu3_lbl6 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company registration country.
        /// </summary>
        internal static string setup_menu3_lbl6_guide {
            get {
                return ResourceManager.GetString("setup_menu3_lbl6_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Country.
        /// </summary>
        internal static string setup_menu3_lbl7 {
            get {
                return ResourceManager.GetString("setup_menu3_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Users who are qualified to use this company in the system, to unlink the user it is necessary to double-click the line.
        /// </summary>
        internal static string setup_menu3_lbl7_guide {
            get {
                return ResourceManager.GetString("setup_menu3_lbl7_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Users who are not qualified to use this company in the system, to link the user it is necessary to double-click..
        /// </summary>
        internal static string setup_menu3_lbl8_guide {
            get {
                return ResourceManager.GetString("setup_menu3_lbl8_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Actions.
        /// </summary>
        internal static string setup_menu3_right_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu3_right_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Entity Selection.
        /// </summary>
        internal static string setup_menu3_right_lbl2 {
            get {
                return ResourceManager.GetString("setup_menu3_right_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Operation.
        /// </summary>
        internal static string setup_menu3_right_lbl3 {
            get {
                return ResourceManager.GetString("setup_menu3_right_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a System Logs.
        /// </summary>
        internal static string setup_menu4 {
            get {
                return ResourceManager.GetString("setup_menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Date.
        /// </summary>
        internal static string setup_menu4_col1 {
            get {
                return ResourceManager.GetString("setup_menu4_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Module.
        /// </summary>
        internal static string setup_menu4_col2 {
            get {
                return ResourceManager.GetString("setup_menu4_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Name.
        /// </summary>
        internal static string setup_menu4_col3 {
            get {
                return ResourceManager.GetString("setup_menu4_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Action.
        /// </summary>
        internal static string setup_menu4_col4 {
            get {
                return ResourceManager.GetString("setup_menu4_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Log.
        /// </summary>
        internal static string setup_menu4_col5 {
            get {
                return ResourceManager.GetString("setup_menu4_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a System Logs.
        /// </summary>
        internal static string setup_menu4_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu4_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Portal Locador.
        /// </summary>
        internal static string setup_menu5 {
            get {
                return ResourceManager.GetString("setup_menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Framework.
        /// </summary>
        internal static string setup_menu6 {
            get {
                return ResourceManager.GetString("setup_menu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Component.
        /// </summary>
        internal static string setup_menu6_1 {
            get {
                return ResourceManager.GetString("setup_menu6-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Framework - Component.
        /// </summary>
        internal static string setup_menu6_1_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu6-1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Product.
        /// </summary>
        internal static string setup_menu6_2 {
            get {
                return ResourceManager.GetString("setup_menu6-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Framework - Product.
        /// </summary>
        internal static string setup_menu6_2_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu6-2_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Basis.
        /// </summary>
        internal static string setup_menu6_3 {
            get {
                return ResourceManager.GetString("setup_menu6-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Framework - Contract Basis.
        /// </summary>
        internal static string setup_menu6_3_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu6-3_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modality.
        /// </summary>
        internal static string setup_menu6_4 {
            get {
                return ResourceManager.GetString("setup_menu6-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Framework - Modality.
        /// </summary>
        internal static string setup_menu6_4_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu6-4_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Events.
        /// </summary>
        internal static string setup_menu6_5 {
            get {
                return ResourceManager.GetString("setup_menu6-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Framework - Events.
        /// </summary>
        internal static string setup_menu6_5_lbl1 {
            get {
                return ResourceManager.GetString("setup_menu6-5_lbl1", resourceCulture);
            }
        }
    }
}
