//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tipologia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tipologia() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Tipologia", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/Tipologia/en-US.
        /// </summary>
        internal static string tipologia_content_tutorial {
            get {
                return ResourceManager.GetString("tipologia_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Typology.
        /// </summary>
        internal static string tipologia_grid1_col1 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Depreciation.
        /// </summary>
        internal static string tipologia_grid1_col10 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Remeasurement.
        /// </summary>
        internal static string tipologia_grid1_col11 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Source.
        /// </summary>
        internal static string tipologia_grid1_col2 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Capital.
        /// </summary>
        internal static string tipologia_grid1_col3 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a USGAAP.
        /// </summary>
        internal static string tipologia_grid1_col4 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tax Recovery.
        /// </summary>
        internal static string tipologia_grid1_col5 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Readjustments.
        /// </summary>
        internal static string tipologia_grid1_col6 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Grace.
        /// </summary>
        internal static string tipologia_grid1_col7 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Flow.
        /// </summary>
        internal static string tipologia_grid1_col8 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calculation.
        /// </summary>
        internal static string tipologia_grid1_col9 {
            get {
                return ResourceManager.GetString("tipologia_grid1_col9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Typology.
        /// </summary>
        internal static string tipologia_grid2_col1 {
            get {
                return ResourceManager.GetString("tipologia_grid2_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Corporate.
        /// </summary>
        internal static string tipologia_grid2_col2 {
            get {
                return ResourceManager.GetString("tipologia_grid2_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Quiz.
        /// </summary>
        internal static string tipologia_label1 {
            get {
                return ResourceManager.GetString("tipologia_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Available Types.
        /// </summary>
        internal static string tipologia_label2 {
            get {
                return ResourceManager.GetString("tipologia_label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Associated Typologies.
        /// </summary>
        internal static string tipologia_label3 {
            get {
                return ResourceManager.GetString("tipologia_label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User action.
        /// </summary>
        internal static string tipologia_quickguide_acao {
            get {
                return ResourceManager.GetString("tipologia_quickguide_acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the structure of the economic GROUP, COMPANY, BRANCH or STORE..
        /// </summary>
        internal static string tipologia_quickguide_empresa {
            get {
                return ResourceManager.GetString("tipologia_quickguide_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the type of contract associated with the store.
        /// </summary>
        internal static string tipologia_quickguide_grid1 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Area designed to display the typologies associated with the Store. &lt;br/&gt; These Typologies will be available for use in contracts. To disassociate a typology it is necessary to double-click under the line..
        /// </summary>
        internal static string tipologia_quickguide_grid2 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string tipologia_quickguide_grid2_col1 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform if the Depreciation will be calculated in a LINEAR way or if there will be different values for different periods..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col10 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the structure of the economic GROUP, COMPANY, BRANCH or STORE..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col11 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a The type of contract is national (only used in your country) or worldwide (the same model is used in all countries..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col2 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Answer whether the contract registration company is publicly traded (trades its shares on stock exchanges) or closed (belongs to shareholder partners)..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col3 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Respond if the contracting company provides accounting information in the American standard (USA) of generally accepted accounting practices..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col4 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform if the registration agreement allows the recovery of taxes. Consult your company&apos;s tax department.
        /// </summary>
        internal static string tipologia_quickguide_grid2_col5 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform if the contract is subject to periodic price adjustment..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col6 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform if the contract has a grace period, that is, a period when you own a property, for example, your company will not pay rent for a period..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col7 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform if the Contract Flow of Payments is UNIFORM, that is, it starts and ends with the same amount or if NOT UNIFORM having different installments in different periods..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col8 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform whether the CASH FLOW to calculate the NPV - Net Present Value of the contract will be calculated using the Price or Linear Table method..
        /// </summary>
        internal static string tipologia_quickguide_grid2_col9 {
            get {
                return ResourceManager.GetString("tipologia_quickguide_grid2_col9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a When placing the mouse over a field, an explanatory text for the field will be displayed in this box..
        /// </summary>
        internal static string tipologia_quickguide_ini {
            get {
                return ResourceManager.GetString("tipologia_quickguide_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract registration requires a TYPOLOGY. The typology is the form of recording, calculating and recording data for each TYPE of contract. You need to choose the TYPOLOGY and associate it with the contract registration. TYPOLOGY is a set of information required by the CONTRACT. To help you choose the alternative in each “COLUMN” of the Grid and Nesta presents the appropriate TYPE. If Nesta responds as “DOESN&apos;T EXIST”, open a call and we will send you the TYPOLOGY..
        /// </summary>
        internal static string tipologia_quickguide_quiz {
            get {
                return ResourceManager.GetString("tipologia_quickguide_quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract registration requires a TYPOLOGY. The typology is the form of recording, calculating and recording data for each TYPE of contract. You need to choose the TYPOLOGY and associate it with the contract registration. TYPOLOGY is a set of information required by the CONTRACT. To help you choose the alternative in each “COLUMN” of the Grid and Nesta presents the appropriate TYPE. If Nesta responds as “DOESN&apos;T EXIST”, open a call and we will send you the TYPOLOGY..
        /// </summary>
        internal static string tipologia_quickguide_titulo {
            get {
                return ResourceManager.GetString("tipologia_quickguide_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a You understand that for the registration of a CONTRACT you need to choose the TYPE of contract, that is, the model that will support the registration, calculations and accounting records guided by IFRS 16. The models change according to the purpose of the contract, conditions and special situations that your company may require due to corporate organization and industry..
        /// </summary>
        internal static string tipologia_quiz {
            get {
                return ResourceManager.GetString("tipologia_quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string tipologia_quiz_10_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_10-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string tipologia_quiz_10_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_10-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a National.
        /// </summary>
        internal static string tipologia_quiz_1_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Global.
        /// </summary>
        internal static string tipologia_quiz_1_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Open.
        /// </summary>
        internal static string tipologia_quiz_2_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closed.
        /// </summary>
        internal static string tipologia_quiz_2_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_2-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string tipologia_quiz_3_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_3-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string tipologia_quiz_3_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_3-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string tipologia_quiz_4_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_4-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string tipologia_quiz_4_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_4-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string tipologia_quiz_5_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_5-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string tipologia_quiz_5_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_5-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string tipologia_quiz_6_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_6-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string tipologia_quiz_6_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_6-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Uniform.
        /// </summary>
        internal static string tipologia_quiz_7_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_7-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No Uniform.
        /// </summary>
        internal static string tipologia_quiz_7_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_7-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Table Price.
        /// </summary>
        internal static string tipologia_quiz_8_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_8-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Linear.
        /// </summary>
        internal static string tipologia_quiz_8_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_8-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Linear.
        /// </summary>
        internal static string tipologia_quiz_9_1 {
            get {
                return ResourceManager.GetString("tipologia_quiz_9-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Differentiated.
        /// </summary>
        internal static string tipologia_quiz_9_2 {
            get {
                return ResourceManager.GetString("tipologia_quiz_9-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User action.
        /// </summary>
        internal static string tipologia_right_lbl1 {
            get {
                return ResourceManager.GetString("tipologia_right_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the Entity.
        /// </summary>
        internal static string tipologia_right_lbl2 {
            get {
                return ResourceManager.GetString("tipologia_right_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Typology.
        /// </summary>
        internal static string tipologia_tituloPag {
            get {
                return ResourceManager.GetString("tipologia_tituloPag", resourceCulture);
            }
        }
    }
}
