//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserProfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfile() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserProfile", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New password does not match with Confirm Password..
        /// </summary>
        internal static string CustomValidator1_1 {
            get {
                return ResourceManager.GetString("CustomValidator1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Current password does not match..
        /// </summary>
        internal static string CustomValidator1_2 {
            get {
                return ResourceManager.GetString("CustomValidator1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Credentials are not valid for authentication because they have been used less than a year ago..
        /// </summary>
        internal static string CustomValidator1_3 {
            get {
                return ResourceManager.GetString("CustomValidator1-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Default Language required.
        /// </summary>
        internal static string CustomValidator1_4 {
            get {
                return ResourceManager.GetString("CustomValidator1-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Profile.
        /// </summary>
        internal static string menu1 {
            get {
                return ResourceManager.GetString("menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Current password.
        /// </summary>
        internal static string menu1_lbl1 {
            get {
                return ResourceManager.GetString("menu1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New password.
        /// </summary>
        internal static string menu1_lbl2 {
            get {
                return ResourceManager.GetString("menu1_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Confirm password.
        /// </summary>
        internal static string menu1_lbl3 {
            get {
                return ResourceManager.GetString("menu1_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Change Password.
        /// </summary>
        internal static string menu1_lbl4 {
            get {
                return ResourceManager.GetString("menu1_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Default Language.
        /// </summary>
        internal static string menu1_lbl5 {
            get {
                return ResourceManager.GetString("menu1_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a WhatsApp number.
        /// </summary>
        internal static string menu1_lbl6 {
            get {
                return ResourceManager.GetString("menu1_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Change Password.
        /// </summary>
        internal static string menu1_titulo1 {
            get {
                return ResourceManager.GetString("menu1_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Registration data.
        /// </summary>
        internal static string menu1_titulo2 {
            get {
                return ResourceManager.GetString("menu1_titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Notification.
        /// </summary>
        internal static string menu2 {
            get {
                return ResourceManager.GetString("menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Received.
        /// </summary>
        internal static string menu2_grid1_col1 {
            get {
                return ResourceManager.GetString("menu2_grid1_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a From.
        /// </summary>
        internal static string menu2_grid1_col2 {
            get {
                return ResourceManager.GetString("menu2_grid1_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Notification.
        /// </summary>
        internal static string menu2_grid1_col3 {
            get {
                return ResourceManager.GetString("menu2_grid1_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Read.
        /// </summary>
        internal static string menu2_grid1_col4 {
            get {
                return ResourceManager.GetString("menu2_grid1_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sent.
        /// </summary>
        internal static string menu2_grid2_col1 {
            get {
                return ResourceManager.GetString("menu2_grid2_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a To.
        /// </summary>
        internal static string menu2_grid2_col2 {
            get {
                return ResourceManager.GetString("menu2_grid2_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Notification.
        /// </summary>
        internal static string menu2_grid2_col3 {
            get {
                return ResourceManager.GetString("menu2_grid2_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Read.
        /// </summary>
        internal static string menu2_grid2_col4 {
            get {
                return ResourceManager.GetString("menu2_grid2_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Notifications Received.
        /// </summary>
        internal static string menu2_titulo1 {
            get {
                return ResourceManager.GetString("menu2_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Notifications Sent.
        /// </summary>
        internal static string menu2_titulo2 {
            get {
                return ResourceManager.GetString("menu2_titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/usuario/en-US.
        /// </summary>
        internal static string userprofile_content_tutorial {
            get {
                return ResourceManager.GetString("userprofile_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Data: Area destined to changes to the user logged in the system, changes to password, default language and WhatsApp number &lt;br/&gt; Notifications: Area destined to view the notifications sent and received..
        /// </summary>
        internal static string user_menu {
            get {
                return ResourceManager.GetString("user_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Field for entering the current password.
        /// </summary>
        internal static string user_menu1_lbl1_guide {
            get {
                return ResourceManager.GetString("user_menu1_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New password consisting of 8 characters: uppercase letter, special character, number and lowercase letter.
        /// </summary>
        internal static string user_menu1_lbl2_guide {
            get {
                return ResourceManager.GetString("user_menu1_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Confirm new password.
        /// </summary>
        internal static string user_menu1_lbl3_guide {
            get {
                return ResourceManager.GetString("user_menu1_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Feature that defines whether the password change feature is turned on..
        /// </summary>
        internal static string user_menu1_lbl4_guide {
            get {
                return ResourceManager.GetString("user_menu1_lbl4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Default language for system translation automatically.
        /// </summary>
        internal static string user_menu1_lbl5_guide {
            get {
                return ResourceManager.GetString("user_menu1_lbl5_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contact number to receive notifications via WhatsApp.
        /// </summary>
        internal static string user_menu1_lbl6_guide {
            get {
                return ResourceManager.GetString("user_menu1_lbl6_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Notifications that were sent to the logged in user, these notifications when they are in bold font are unread notifications, to confirm the reading it is necessary to double-click..
        /// </summary>
        internal static string user_menu2_lbl1_guide {
            get {
                return ResourceManager.GetString("user_menu2_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Notifications that were sent by the logged in user, in this view do not have direct actions on the grid, they are just notifications sent by the user..
        /// </summary>
        internal static string user_menu2_lbl2_guide {
            get {
                return ResourceManager.GetString("user_menu2_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Password must contain at least 8 characters (uppercase letter, special character, number and lowercase letter).
        /// </summary>
        internal static string user_password_error {
            get {
                return ResourceManager.GetString("user_password_error", resourceCulture);
            }
        }
    }
}
