//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Aquisicao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aquisicao() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Aquisicao", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Events.
        /// </summary>
        internal static string aquisicao_aditamento_aba1 {
            get {
                return ResourceManager.GetString("aquisicao_aditamento_aba1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Dismemberments.
        /// </summary>
        internal static string aquisicao_aditamento_aba2 {
            get {
                return ResourceManager.GetString("aquisicao_aditamento_aba2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select amendment the event and date from.
        /// </summary>
        internal static string aquisicao_aditamento_lbl1 {
            get {
                return ResourceManager.GetString("aquisicao_aditamento_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Insert the justification text for the contractual amendment.
        /// </summary>
        internal static string aquisicao_aditamento_lbl2 {
            get {
                return ResourceManager.GetString("aquisicao_aditamento_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Characters: 255.
        /// </summary>
        internal static string aquisicao_aditamento_lbl3 {
            get {
                return ResourceManager.GetString("aquisicao_aditamento_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Justification must contain between 20 and 255 characters..
        /// </summary>
        internal static string aquisicao_aditamento_lbl4 {
            get {
                return ResourceManager.GetString("aquisicao_aditamento_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select amendment date from.
        /// </summary>
        internal static string aquisicao_aditamento_lbl5 {
            get {
                return ResourceManager.GetString("aquisicao_aditamento_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Amendment.
        /// </summary>
        internal static string aquisicao_aditamento_titulo {
            get {
                return ResourceManager.GetString("aquisicao_aditamento_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/contrato/en-US.
        /// </summary>
        internal static string aquisicao_content_tutorial {
            get {
                return ResourceManager.GetString("aquisicao_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Text about the process of deleting a contract.
        /// </summary>
        internal static string aquisicao_delete_texto {
            get {
                return ResourceManager.GetString("aquisicao_delete_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exclusion Process.
        /// </summary>
        internal static string aquisicao_delete_titulo {
            get {
                return ResourceManager.GetString("aquisicao_delete_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a There is no Produt associated to this Entity.
        /// </summary>
        internal static string aquisicao_erro_tipologia {
            get {
                return ResourceManager.GetString("aquisicao_erro_tipologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Justification.
        /// </summary>
        internal static string aquisicao_historico_col1 {
            get {
                return ResourceManager.GetString("aquisicao_historico_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract basis.
        /// </summary>
        internal static string aquisicao_historico_col2 {
            get {
                return ResourceManager.GetString("aquisicao_historico_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string aquisicao_historico_col3 {
            get {
                return ResourceManager.GetString("aquisicao_historico_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Amendment.
        /// </summary>
        internal static string aquisicao_historico_col4 {
            get {
                return ResourceManager.GetString("aquisicao_historico_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sequence.
        /// </summary>
        internal static string aquisicao_historico_col5 {
            get {
                return ResourceManager.GetString("aquisicao_historico_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Change History.
        /// </summary>
        internal static string aquisicao_historico_titulo {
            get {
                return ResourceManager.GetString("aquisicao_historico_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Amendment.
        /// </summary>
        internal static string aquisição_btn_aditamento {
            get {
                return ResourceManager.GetString("aquisição_btn_aditamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a When clicking on the AMENDMENT button, the system enters into a contractual amendment mode allowing the user, upon justification, to change the contract properties that impact the results of the calculations performed by the system..
        /// </summary>
        internal static string aquisição_btn_aditamento_guide {
            get {
                return ResourceManager.GetString("aquisição_btn_aditamento_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a By clicking on the HISTORY button, the system shows in chronological order the history of all the modifications suffered by the contract since its creation..
        /// </summary>
        internal static string aquisição_btn_historico_guide {
            get {
                return ResourceManager.GetString("aquisição_btn_historico_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a By clicking on the DUPLICATE button, the system creates a copy (clone) with the main properties of the contract being edited. This feature is widely used in the creation of contracts that have similar characteristics..
        /// </summary>
        internal static string aquisição_btn_replicar_guide {
            get {
                return ResourceManager.GetString("aquisição_btn_replicar_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a By clicking on the OK button the contract will be deleted from the system if and only if it fully meets the following conditions: &lt;br/&gt; &lt;br/&gt;. There is no End of Exercise note. &lt;/br&gt;. It does not have an Accounting Interface annotation. &lt;/br&gt;. There is no note on Financial Transactions (Cash Monitoring). &lt;/br&gt;. There is no commitment and / or payment authorization (APR) note committed or carried out. &lt;/br&gt; &lt;/br&gt; If all of the above conditions are met, the Real, Nominal, Inflated, Currency and USGaap scenari [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string aquisição_delete_texto {
            get {
                return ResourceManager.GetString("aquisição_delete_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exclusion Process.
        /// </summary>
        internal static string aquisição_delete_titulo {
            get {
                return ResourceManager.GetString("aquisição_delete_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exclusion Process.
        /// </summary>
        internal static string aquisição_excluir_texto1 {
            get {
                return ResourceManager.GetString("aquisição_excluir_texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Text about the process of deleting a contract.
        /// </summary>
        internal static string aquisição_excluir_texto2 {
            get {
                return ResourceManager.GetString("aquisição_excluir_texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Until.
        /// </summary>
        internal static string aquisição_grid_ate {
            get {
                return ResourceManager.GetString("aquisição_grid_ate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ref.
        /// </summary>
        internal static string aquisição_grid_data {
            get {
                return ResourceManager.GetString("aquisição_grid_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a From.
        /// </summary>
        internal static string aquisição_grid_de {
            get {
                return ResourceManager.GetString("aquisição_grid_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string aquisição_grid_valor {
            get {
                return ResourceManager.GetString("aquisição_grid_valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Corporative Structure.
        /// </summary>
        internal static string aquisição_grp1_lbl1 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Value.
        /// </summary>
        internal static string aquisição_grp1_lbl10 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Enter the total value of the contract. The value is always the total total contracted value noted in the contract..
        /// </summary>
        internal static string aquisição_grp1_lbl10_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl10_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Payments Start.
        /// </summary>
        internal static string aquisição_grp1_lbl11 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract payment flow start date.
        /// </summary>
        internal static string aquisição_grp1_lbl11_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl11_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Payments Finish.
        /// </summary>
        internal static string aquisição_grp1_lbl12 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a End date of contract payment flow.
        /// </summary>
        internal static string aquisição_grp1_lbl12_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl12_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Structure.
        /// </summary>
        internal static string aquisição_grp1_lbl13 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the reason for the contract..
        /// </summary>
        internal static string aquisição_grp1_lbl13_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl13_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Product Class.
        /// </summary>
        internal static string aquisição_grp1_lbl14 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Text for PENDING Class.
        /// </summary>
        internal static string aquisição_grp1_lbl14_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl14_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Product.
        /// </summary>
        internal static string aquisição_grp1_lbl15 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the type of contract that can support the calculations and treatment of the contract you want to register..
        /// </summary>
        internal static string aquisição_grp1_lbl15_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl15_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Portfolio.
        /// </summary>
        internal static string aquisição_grp1_lbl16 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a The portfolio is a classifier created previously to select contracts in different classifications. Choose the portfolio that will add the contract being registered..
        /// </summary>
        internal static string aquisição_grp1_lbl16_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl16_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the structure of the economic GROUP, the COMPANY or the branch you intend to subordinate to the contract you are going to register..
        /// </summary>
        internal static string aquisição_grp1_lbl1_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Building.
        /// </summary>
        internal static string aquisição_grp1_lbl2 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a This field requires prior registration. Text for PENDING Property.
        /// </summary>
        internal static string aquisição_grp1_lbl2_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Internal Id.
        /// </summary>
        internal static string aquisição_grp1_lbl3 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Operator.
        /// </summary>
        internal static string aquisição_grp1_lbl31 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exclusive use of the system.
        /// </summary>
        internal static string aquisição_grp1_lbl31_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl31_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exclusive use of the system.
        /// </summary>
        internal static string aquisição_grp1_lbl3_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Process Number.
        /// </summary>
        internal static string aquisição_grp1_lbl4 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Enter the contract number here. This number is just an identifier that will guide the user in searches. The numerical control of the contract is internal and the responsibility of the system..
        /// </summary>
        internal static string aquisição_grp1_lbl4_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string aquisição_grp1_lbl5 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Give the contract a reference name. Use a reference that tells you the purpose of the contract..
        /// </summary>
        internal static string aquisição_grp1_lbl5_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl5_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Auxiliary Number.
        /// </summary>
        internal static string aquisição_grp1_lbl6 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a If you need to supplement the Process Number, please write down an Auxiliary Code..
        /// </summary>
        internal static string aquisição_grp1_lbl6_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl6_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Release date.
        /// </summary>
        internal static string aquisição_grp1_lbl7 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Enter the start date of the contract. Usually the date of signing the contract..
        /// </summary>
        internal static string aquisição_grp1_lbl7_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl7_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Signature date.
        /// </summary>
        internal static string aquisição_grp1_lbl8 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract signing date.
        /// </summary>
        internal static string aquisição_grp1_lbl8_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl8_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closing Date.
        /// </summary>
        internal static string aquisição_grp1_lbl9 {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Date on which the contract signed between the parties ends.
        /// </summary>
        internal static string aquisição_grp1_lbl9_guide {
            get {
                return ResourceManager.GetString("aquisição_grp1_lbl9_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a  | Internal Id:.
        /// </summary>
        internal static string aquisição_grp1_subtitulo1 {
            get {
                return ResourceManager.GetString("aquisição_grp1_subtitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a General Information.
        /// </summary>
        internal static string aquisição_grp1_titulo1 {
            get {
                return ResourceManager.GetString("aquisição_grp1_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a The General Information tab shows the characteristics of identification, topology, value and duration of the contract..
        /// </summary>
        internal static string aquisição_grp1_titulo1_quickguide {
            get {
                return ResourceManager.GetString("aquisição_grp1_titulo1_quickguide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Favored.
        /// </summary>
        internal static string aquisição_grp2_lbl1 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the Favored of the contract. It must be previously registered. To find it, start typing words contained in your name or business name and the system will debug the search until you find the desired supplier..
        /// </summary>
        internal static string aquisição_grp2_lbl1_guide {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Beneficiary.
        /// </summary>
        internal static string aquisição_grp2_lbl2 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the BENEFICIARY of the contract. It must be previously registered. To find it, start typing words contained in your name or business name and the system will debug the search until you find the desired supplier..
        /// </summary>
        internal static string aquisição_grp2_lbl2_guide {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string aquisição_grp2_lbl3 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Classification or status of the contract. Indicates whether it is ACTIVE or CLOSED. By default, in the inclusion, the system presents the field filled in as ACTIVE..
        /// </summary>
        internal static string aquisição_grp2_lbl3_guide {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Uniform Installment.
        /// </summary>
        internal static string aquisição_grp2_lbl4 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string aquisição_grp2_lbl4_1 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl4.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string aquisição_grp2_lbl4_2 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl4.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform if the contract installments are uniform.
        /// </summary>
        internal static string aquisição_grp2_lbl4_guide {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Grace Period.
        /// </summary>
        internal static string aquisição_grp2_lbl5 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string aquisição_grp2_lbl5_1 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl5.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string aquisição_grp2_lbl5_2 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl5.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform if there is a grace period to start contract charges.
        /// </summary>
        internal static string aquisição_grp2_lbl5_guide {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl5_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Deployed Balance.
        /// </summary>
        internal static string aquisição_grp2_lbl6 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Full.
        /// </summary>
        internal static string aquisição_grp2_lbl6_1 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl6.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Partial.
        /// </summary>
        internal static string aquisição_grp2_lbl6_2 {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl6.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inform whether the balance applied to the contract will be total or partial.
        /// </summary>
        internal static string aquisição_grp2_lbl6_guide {
            get {
                return ResourceManager.GetString("aquisição_grp2_lbl6_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Classification.
        /// </summary>
        internal static string aquisição_grp2_titulo {
            get {
                return ResourceManager.GetString("aquisição_grp2_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a The Contract Classification tab shows the parameters that determine the filling in of the properties contained in the Contract Basis tab..
        /// </summary>
        internal static string aquisição_grp2_titulo1_quickguide {
            get {
                return ResourceManager.GetString("aquisição_grp2_titulo1_quickguide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract basis.
        /// </summary>
        internal static string aquisição_grp3_titulo {
            get {
                return ResourceManager.GetString("aquisição_grp3_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a The Contract Basis tab shows the properties and criteria that are essential for generating the cash flow calculations, financial statements and accounting statements of the contracts. These properties can be edited by adding the contract, as they change the results of the calculations performed by the system..
        /// </summary>
        internal static string aquisição_grp3_titulo1_quickguide {
            get {
                return ResourceManager.GetString("aquisição_grp3_titulo1_quickguide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        internal static string aquisição_grp4_btn {
            get {
                return ResourceManager.GetString("aquisição_grp4_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a #ID.
        /// </summary>
        internal static string aquisição_grp4_grid_col1 {
            get {
                return ResourceManager.GetString("aquisição_grp4_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File Name.
        /// </summary>
        internal static string aquisição_grp4_grid_col2 {
            get {
                return ResourceManager.GetString("aquisição_grp4_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Attachments.
        /// </summary>
        internal static string aquisição_grp4_titulo {
            get {
                return ResourceManager.GetString("aquisição_grp4_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Use the Funds tab to link contracted and accessory funds to the contract. Click on the ADD + icon to link the amount to the contract, choosing the amount, the basis negotiated and the form of payment. Click on the TRASH icon to delete unlink the money from the contract..
        /// </summary>
        internal static string aquisição_grp4_titulo1_quickguide {
            get {
                return ResourceManager.GetString("aquisição_grp4_titulo1_quickguide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string aquisição_grp5_col1 {
            get {
                return ResourceManager.GetString("aquisição_grp5_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Basis.
        /// </summary>
        internal static string aquisição_grp5_col2 {
            get {
                return ResourceManager.GetString("aquisição_grp5_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Payment Type.
        /// </summary>
        internal static string aquisição_grp5_col3 {
            get {
                return ResourceManager.GetString("aquisição_grp5_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Invoice Day.
        /// </summary>
        internal static string aquisição_grp5_col4 {
            get {
                return ResourceManager.GetString("aquisição_grp5_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Credit Account.
        /// </summary>
        internal static string aquisição_grp5_col5 {
            get {
                return ResourceManager.GetString("aquisição_grp5_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Debit Account.
        /// </summary>
        internal static string aquisição_grp5_col6 {
            get {
                return ResourceManager.GetString("aquisição_grp5_col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funds.
        /// </summary>
        internal static string aquisição_grp5_titulo {
            get {
                return ResourceManager.GetString("aquisição_grp5_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Use the ATTACHMENTS tab to store the document base of contracts in the system. Click on the SEARCH button to upload (upload) the document linked to the contract. Click the DOCUMENT icon  to open and read the document. Click on the TRASH icon  to delete the document from the database and unlink it from the contract..
        /// </summary>
        internal static string aquisição_grp5_titulo1_quickguide {
            get {
                return ResourceManager.GetString("aquisição_grp5_titulo1_quickguide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Folder not found.
        /// </summary>
        internal static string aquisição_lbl_FileManager {
            get {
                return ResourceManager.GetString("aquisição_lbl_FileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Process Number.
        /// </summary>
        internal static string aquisição_right_grid_col1 {
            get {
                return ResourceManager.GetString("aquisição_right_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Corporative structure.
        /// </summary>
        internal static string aquisição_right_grid_col2 {
            get {
                return ResourceManager.GetString("aquisição_right_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Product.
        /// </summary>
        internal static string aquisição_right_grid_col3 {
            get {
                return ResourceManager.GetString("aquisição_right_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string aquisição_right_grid_col4 {
            get {
                return ResourceManager.GetString("aquisição_right_grid_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a #Prod.
        /// </summary>
        internal static string aquisição_right_grid_col5 {
            get {
                return ResourceManager.GetString("aquisição_right_grid_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a #ID.
        /// </summary>
        internal static string aquisição_right_grid_col6 {
            get {
                return ResourceManager.GetString("aquisição_right_grid_col6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Search.
        /// </summary>
        internal static string aquisição_right_titulo {
            get {
                return ResourceManager.GetString("aquisição_right_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Use the filters to manipulate the sample data. Click on the column title to sort the data in ascending ↑ or descending ↓ order. Double click on the grid line to load the form with all the properties of the selected contract..
        /// </summary>
        internal static string aquisição_right_titulo_guide {
            get {
                return ResourceManager.GetString("aquisição_right_titulo_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Registration.
        /// </summary>
        internal static string aquisição_tituloPag {
            get {
                return ResourceManager.GetString("aquisição_tituloPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Import.
        /// </summary>
        internal static string umbrella_grp4_grid_btn1 {
            get {
                return ResourceManager.GetString("umbrella_grp4_grid_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string umbrella_grp4_grid_col1 {
            get {
                return ResourceManager.GetString("umbrella_grp4_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Process Number.
        /// </summary>
        internal static string umbrella_grp4_grid_col2 {
            get {
                return ResourceManager.GetString("umbrella_grp4_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string umbrella_grp4_grid_col3 {
            get {
                return ResourceManager.GetString("umbrella_grp4_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string umbrella_grp4_grid_col4 {
            get {
                return ResourceManager.GetString("umbrella_grp4_grid_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string umbrella_grp4_grid_col5 {
            get {
                return ResourceManager.GetString("umbrella_grp4_grid_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a SubContracts.
        /// </summary>
        internal static string umbrella_grp4_titulo1 {
            get {
                return ResourceManager.GetString("umbrella_grp4_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contracts Lump Sum .
        /// </summary>
        internal static string umbrella_right_titulo {
            get {
                return ResourceManager.GetString("umbrella_right_titulo", resourceCulture);
            }
        }
    }
}
