//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClasseContabil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClasseContabil() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ClasseContabil", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/classecontabil/en-US.
        /// </summary>
        internal static string classecontabil_content_tutorial {
            get {
                return ResourceManager.GetString("classecontabil_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fund.
        /// </summary>
        internal static string classecontabil_grid_col1 {
            get {
                return ResourceManager.GetString("classecontabil_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Credit Account.
        /// </summary>
        internal static string classecontabil_grid_col2 {
            get {
                return ResourceManager.GetString("classecontabil_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Credit Name.
        /// </summary>
        internal static string classecontabil_grid_col3 {
            get {
                return ResourceManager.GetString("classecontabil_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Debit Account.
        /// </summary>
        internal static string classecontabil_grid_col4 {
            get {
                return ResourceManager.GetString("classecontabil_grid_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Debit Name.
        /// </summary>
        internal static string classecontabil_grid_col5 {
            get {
                return ResourceManager.GetString("classecontabil_grid_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string classecontabil_label_1 {
            get {
                return ResourceManager.GetString("classecontabil_label_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Number.
        /// </summary>
        internal static string classecontabil_label_2 {
            get {
                return ResourceManager.GetString("classecontabil_label_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Action.
        /// </summary>
        internal static string classecontabil_quickguide_acao {
            get {
                return ResourceManager.GetString("classecontabil_quickguide_acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Establish the link between the contractual amounts and the debit and credit accounting accounts for accounting purposes. When clicking on the VALIDATE button, the system highlights the changes made to the grid without saving them in the database. When clicking on the SAVE button, the system saves the changes made to the grid in the database. When you click on the CANCEL button, the system discards all changes made to the grid, restoring the original data prior to the changes..
        /// </summary>
        internal static string classecontabil_quickguide_grid {
            get {
                return ResourceManager.GetString("classecontabil_quickguide_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a When placing the mouse over a field, an explanatory text regarding the content will be displayed in this box..
        /// </summary>
        internal static string classecontabil_quickguide_ini {
            get {
                return ResourceManager.GetString("classecontabil_quickguide_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description of the Product for which the links between the contractual amounts (or accounting modalities) and the debit and credit accounting accounts will be established for accounting purposes (generation of accounting entries) at the end of each year-end closing.
        /// </summary>
        internal static string classecontabil_quickguide_lbl1 {
            get {
                return ResourceManager.GetString("classecontabil_quickguide_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the Product for which the links between the contractual amounts (or accounting modalities) and the debit and credit accounting accounts will be established for accounting purposes (generation of accounting entries) at the end of each year-end closing.
        /// </summary>
        internal static string classecontabil_quickguide_produto {
            get {
                return ResourceManager.GetString("classecontabil_quickguide_produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the structure of the economic GROUP, COMPANY, BRANCH or STORE.
        /// </summary>
        internal static string classecontabil_quickguide_selecione {
            get {
                return ResourceManager.GetString("classecontabil_quickguide_selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Titulo.
        /// </summary>
        internal static string classecontabil_quickguide_titulo {
            get {
                return ResourceManager.GetString("classecontabil_quickguide_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Action.
        /// </summary>
        internal static string classecontabil_right_lbl1 {
            get {
                return ResourceManager.GetString("classecontabil_right_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select Entity.
        /// </summary>
        internal static string classecontabil_right_lbl2 {
            get {
                return ResourceManager.GetString("classecontabil_right_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select Product.
        /// </summary>
        internal static string classecontabil_right_lbl3 {
            get {
                return ResourceManager.GetString("classecontabil_right_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accounting Class.
        /// </summary>
        internal static string classecontabil_tituloPag {
            get {
                return ResourceManager.GetString("classecontabil_tituloPag", resourceCulture);
            }
        }
    }
}
