//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ETTJ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ETTJ() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ETTJ", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/ettj/en-US.
        /// </summary>
        internal static string ettj_content_tutorial {
            get {
                return ResourceManager.GetString("ettj_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        internal static string ettj_guia1 {
            get {
                return ResourceManager.GetString("ettj_guia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string ettj_guia1_guide {
            get {
                return ResourceManager.GetString("ettj_guia1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Book.
        /// </summary>
        internal static string ettj_guia1_lbl1 {
            get {
                return ResourceManager.GetString("ettj_guia1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a A portfolio collection in which the EETJ Curve configured on this screen will be applied..
        /// </summary>
        internal static string ettj_guia1_lbl1_guide {
            get {
                return ResourceManager.GetString("ettj_guia1_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Scenario.
        /// </summary>
        internal static string ettj_guia1_lbl2 {
            get {
                return ResourceManager.GetString("ettj_guia1_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Display of which imported scenario is active for the system to use as the basis for calculations..
        /// </summary>
        internal static string ettj_guia1_lbl2_guide {
            get {
                return ResourceManager.GetString("ettj_guia1_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Criterion.
        /// </summary>
        internal static string ettj_guia1_lbl3 {
            get {
                return ResourceManager.GetString("ettj_guia1_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Criterion.
        /// </summary>
        internal static string ettj_guia1_lbl3_guide {
            get {
                return ResourceManager.GetString("ettj_guia1_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string ettj_guia1_lbl4 {
            get {
                return ResourceManager.GetString("ettj_guia1_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name created for the EETJ Curve created..
        /// </summary>
        internal static string ettj_guia1_lbl4_guide {
            get {
                return ResourceManager.GetString("ettj_guia1_lbl4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Scenario.
        /// </summary>
        internal static string ettj_guia2 {
            get {
                return ResourceManager.GetString("ettj_guia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Scenario.
        /// </summary>
        internal static string ettj_guia2_btn1 {
            get {
                return ResourceManager.GetString("ettj_guia2_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Scenario.
        /// </summary>
        internal static string ettj_guia2_btn1_guide {
            get {
                return ResourceManager.GetString("ettj_guia2_btn1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Scenario.
        /// </summary>
        internal static string ettj_guia2_grid_col1 {
            get {
                return ResourceManager.GetString("ettj_guia2_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string ettj_guia2_grid_col2 {
            get {
                return ResourceManager.GetString("ettj_guia2_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string ettj_guia2_grid_col3 {
            get {
                return ResourceManager.GetString("ettj_guia2_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Active.
        /// </summary>
        internal static string ettj_guia2_grid_opt1 {
            get {
                return ResourceManager.GetString("ettj_guia2_grid_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Deactive.
        /// </summary>
        internal static string ettj_guia2_grid_opt2 {
            get {
                return ResourceManager.GetString("ettj_guia2_grid_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Display of all scenarios imported into the ETTJ Curve and display and management of which scenario will be used by the system. &lt;br/&gt; New Scenario: Enables the user to import their own ETTJ Curve with interest rates and interest intervals. On this screen it is possible to download the excel spreadsheet that serves as the basis for filling in the fees..
        /// </summary>
        internal static string ettj_guia2_guide {
            get {
                return ResourceManager.GetString("ettj_guia2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Interest Curve.
        /// </summary>
        internal static string ettj_guia3 {
            get {
                return ResourceManager.GetString("ettj_guia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Graph composed of imported scenarios, the graph will show all scenarios created with an emphasis on the active scenario..
        /// </summary>
        internal static string ettj_guia3_guide {
            get {
                return ResourceManager.GetString("ettj_guia3_guide", resourceCulture);
            }
        }
    }
}
