//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OCRTools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OCRTools() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OCRTools", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Processar OCR.
        /// </summary>
        internal static string ocrtools2_btn1 {
            get {
                return ResourceManager.GetString("ocrtools2_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Processar a leitura dos arquivos de PDF disponíveis para o sistema e posteriormente o preenchimentos dos registros de Boletos sem Layout, Boletos Lidos e Boletos Discrepantes..
        /// </summary>
        internal static string ocrtools2_btn1_guide {
            get {
                return ResourceManager.GetString("ocrtools2_btn1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Boletos sem Layout.
        /// </summary>
        internal static string ocrtools2_guia1 {
            get {
                return ResourceManager.GetString("ocrtools2_guia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exibição dos boletos disponibilizados que não possuem layouts associados, nesse momento é permitido ao usuário associar um Layout ao arquivo PDF ou então criar um novo Layout a partir da tela.&lt;br/&gt;Para alterar os dados é possível clicando duas vezes na linha desejada, Para Inserir deve-se clicar no ícone + e preencher os campos. Para Excluir é necessário clicar no ícone da lixeira. Após qualquer dessas operações é necessário Salvar ou então Descartar..
        /// </summary>
        internal static string ocrtools2_guia1_guide {
            get {
                return ResourceManager.GetString("ocrtools2_guia1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Boletos Lidos.
        /// </summary>
        internal static string ocrtools2_guia2 {
            get {
                return ResourceManager.GetString("ocrtools2_guia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Processar.
        /// </summary>
        internal static string ocrtools2_guia2_btn1 {
            get {
                return ResourceManager.GetString("ocrtools2_guia2_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Processar.
        /// </summary>
        internal static string ocrtools2_guia2_btn1_guide {
            get {
                return ResourceManager.GetString("ocrtools2_guia2_btn1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exibição dos boletos que foram Lidos corretamente e não possuem divergência entre valores descritivos e total do boletos, estes boletos estão prontos para serem processados e enviados ao boletagem.&lt;br/&gt;Para alterar os dados é possível clicando duas vezes na linha desejada, Para Inserir deve-se clicar no ícone + e preencher os campos. Para Excluir é necessário clicar no ícone da lixeira. Após qualquer dessas operações é necessário Salvar ou então Descartar.&lt;br/&gt;Processar: função que irá enviar os registros s [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ocrtools2_guia2_guide {
            get {
                return ResourceManager.GetString("ocrtools2_guia2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Boletos Discrepantes.
        /// </summary>
        internal static string ocrtools2_guia3 {
            get {
                return ResourceManager.GetString("ocrtools2_guia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exibição dos boletos que foram lidos porém existem diferenças entre os valores descritivos e o total do boleto, desta forma o sistema separa o registro para avaliação do layout criado.&lt;br/&gt;Para alterar os dados é possível clicando duas vezes na linha desejada, Para Inserir deve-se clicar no ícone + e preencher os campos. Para Excluir é necessário clicar no ícone da lixeira. Após qualquer dessas operações é necessário Salvar ou então Descartar..
        /// </summary>
        internal static string ocrtools2_guia3_guide {
            get {
                return ResourceManager.GetString("ocrtools2_guia3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string ocrtools_btn1 {
            get {
                return ResourceManager.GetString("ocrtools_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/ocrtools/en-US.
        /// </summary>
        internal static string ocrtools_content_tutorial {
            get {
                return ResourceManager.GetString("ocrtools_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Parametros.
        /// </summary>
        internal static string ocrtools_guia1 {
            get {
                return ResourceManager.GetString("ocrtools_guia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Validar.
        /// </summary>
        internal static string ocrtools_guia1_btn1 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Validar.
        /// </summary>
        internal static string ocrtools_guia1_btn1_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_btn1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Gravar.
        /// </summary>
        internal static string ocrtools_guia1_btn2 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Gravar.
        /// </summary>
        internal static string ocrtools_guia1_btn2_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_btn2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Deletar.
        /// </summary>
        internal static string ocrtools_guia1_btn3 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Deletar.
        /// </summary>
        internal static string ocrtools_guia1_btn3_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_btn3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Texto.
        /// </summary>
        internal static string ocrtools_guia1_lbl1 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Verba?.
        /// </summary>
        internal static string ocrtools_guia1_lbl10 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string ocrtools_guia1_lbl10_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl10_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Classificador.
        /// </summary>
        internal static string ocrtools_guia1_lbl11 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Classificador que servirá como filtro dos dados e organização das informações coletadas pelo OCR, importante que os classificadores Código de Barras, Contrato, Data Vencimento e Total sejam anotadas para controle dos dados capturados pelo OCR..
        /// </summary>
        internal static string ocrtools_guia1_lbl11_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl11_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tipo Dados.
        /// </summary>
        internal static string ocrtools_guia1_lbl12 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Classificar se o dado coleto é um número, uma data ou um texto comum..
        /// </summary>
        internal static string ocrtools_guia1_lbl12_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl12_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Verba.
        /// </summary>
        internal static string ocrtools_guia1_lbl13 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Associar o dado coletado por OCR à uma Verba previamente cadastrada no sistema..
        /// </summary>
        internal static string ocrtools_guia1_lbl13_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl13_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Texto que servirá como guia para encontrar as coordenadas do alvo buscado no arquivo PDF.
        /// </summary>
        internal static string ocrtools_guia1_lbl1_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ocorrência.
        /// </summary>
        internal static string ocrtools_guia1_lbl2 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Campo responsável por definir em qual ocorrência de repetição se dará o resultado final, ou seja, caso esse campo seja preenchido com o numeral 2 o sistema irá pesquisar o texto inserido e, ao encontrar a segunda ocorrência, este será anotada como resultado..
        /// </summary>
        internal static string ocrtools_guia1_lbl2_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Posicionamento.
        /// </summary>
        internal static string ocrtools_guia1_lbl3 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar qual a posição do resultado pretendido com relação ao texto pesquisado, se o resultado estará a esquerda do texto, ou acima, ou a direita ou abaixo..
        /// </summary>
        internal static string ocrtools_guia1_lbl3_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Apenas Cordenadas?.
        /// </summary>
        internal static string ocrtools_guia1_lbl4 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Este recurso ignora as informações de texto, ocorrência e posicionamento e consulta apenas com os dados inseridos como coordenadas..
        /// </summary>
        internal static string ocrtools_guia1_lbl4_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Acima.
        /// </summary>
        internal static string ocrtools_guia1_lbl5 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Possibilita ao usuário ajustar as coordenadas conforme o desejado para atingir o resultado esperado..
        /// </summary>
        internal static string ocrtools_guia1_lbl5_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl5_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Esquerda.
        /// </summary>
        internal static string ocrtools_guia1_lbl6 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Possibilita ao usuário ajustar as coordenadas conforme o desejado para atingir o resultado esperado..
        /// </summary>
        internal static string ocrtools_guia1_lbl6_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl6_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Direita.
        /// </summary>
        internal static string ocrtools_guia1_lbl7 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Possibilita ao usuário ajustar as coordenadas conforme o desejado para atingir o resultado esperado..
        /// </summary>
        internal static string ocrtools_guia1_lbl7_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl7_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Abaixo.
        /// </summary>
        internal static string ocrtools_guia1_lbl8 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Possibilita ao usuário ajustar as coordenadas conforme o desejado para atingir o resultado esperado..
        /// </summary>
        internal static string ocrtools_guia1_lbl8_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl8_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Resultado.
        /// </summary>
        internal static string ocrtools_guia1_lbl9 {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Campo que irá exibir o resultado da consulta no arquivo PDF..
        /// </summary>
        internal static string ocrtools_guia1_lbl9_guide {
            get {
                return ResourceManager.GetString("ocrtools_guia1_lbl9_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Plano Verbas.
        /// </summary>
        internal static string ocrtools_guia2 {
            get {
                return ResourceManager.GetString("ocrtools_guia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string ocrtools_guia2_grid_col1 {
            get {
                return ResourceManager.GetString("ocrtools_guia2_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Classficador.
        /// </summary>
        internal static string ocrtools_guia2_grid_col2 {
            get {
                return ResourceManager.GetString("ocrtools_guia2_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Verba.
        /// </summary>
        internal static string ocrtools_guia2_grid_col3 {
            get {
                return ResourceManager.GetString("ocrtools_guia2_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Carregar PDF.
        /// </summary>
        internal static string ocrtools_lbl1 {
            get {
                return ResourceManager.GetString("ocrtools_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Carregar um arquivo PDF para servir como referência para criação dos layouts e parâmetros de pesquisa..
        /// </summary>
        internal static string ocrtools_lbl1_guide {
            get {
                return ResourceManager.GetString("ocrtools_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Arquivo Carregado:.
        /// </summary>
        internal static string ocrtools_lbl2 {
            get {
                return ResourceManager.GetString("ocrtools_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome do Arquivo Carregado, é possível abrir o arquivo em janela popup..
        /// </summary>
        internal static string ocrtools_lbl2_guide {
            get {
                return ResourceManager.GetString("ocrtools_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Novo Layout.
        /// </summary>
        internal static string ocrtools_lbl3 {
            get {
                return ResourceManager.GetString("ocrtools_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome do nome Layout de leitura OCR..
        /// </summary>
        internal static string ocrtools_lbl3_guide {
            get {
                return ResourceManager.GetString("ocrtools_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar Layout.
        /// </summary>
        internal static string ocrtools_lbl4 {
            get {
                return ResourceManager.GetString("ocrtools_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecione um Layout existente para visualizar os parametros criados e assim gerenciar os dados necessários..
        /// </summary>
        internal static string ocrtools_lbl4_guide {
            get {
                return ResourceManager.GetString("ocrtools_lbl4_guide", resourceCulture);
            }
        }
    }
}
