//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PassivosAquisicao2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PassivosAquisicao2() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PassivosAquisicao2", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string contabil_card1_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contrato.
        /// </summary>
        internal static string contabil_card1_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string contabil_card1_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contraparte.
        /// </summary>
        internal static string contabil_card1_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Índice.
        /// </summary>
        internal static string contabil_card1_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contratos.
        /// </summary>
        internal static string contabil_card1_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card1_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Evento.
        /// </summary>
        internal static string contabil_card2_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Spread.
        /// </summary>
        internal static string contabil_card2_coluna10 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Venc1.
        /// </summary>
        internal static string contabil_card2_coluna11 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Venc2.
        /// </summary>
        internal static string contabil_card2_coluna12 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Taxa.
        /// </summary>
        internal static string contabil_card2_coluna13 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        internal static string contabil_card2_coluna14 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pagamento.
        /// </summary>
        internal static string contabil_card2_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Parc.
        /// </summary>
        internal static string contabil_card2_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Seq.
        /// </summary>
        internal static string contabil_card2_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Dias.
        /// </summary>
        internal static string contabil_card2_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Devedor.
        /// </summary>
        internal static string contabil_card2_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Amortizado.
        /// </summary>
        internal static string contabil_card2_coluna7 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Juros.
        /// </summary>
        internal static string contabil_card2_coluna8 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Comis.
        /// </summary>
        internal static string contabil_card2_coluna9 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fluxo de Caixa.
        /// </summary>
        internal static string contabil_card2_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card2_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Evento.
        /// </summary>
        internal static string contabil_card3_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string contabil_card3_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Débito.
        /// </summary>
        internal static string contabil_card3_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Crédito.
        /// </summary>
        internal static string contabil_card3_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Acumulado.
        /// </summary>
        internal static string contabil_card3_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Saldo Principal.
        /// </summary>
        internal static string contabil_card3_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cotação.
        /// </summary>
        internal static string contabil_card3_coluna7 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Extrato Financeiro.
        /// </summary>
        internal static string contabil_card3_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card3_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        internal static string contabil_card4_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a D/C.
        /// </summary>
        internal static string contabil_card4_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Conta Contábil.
        /// </summary>
        internal static string contabil_card4_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string contabil_card4_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modalidade.
        /// </summary>
        internal static string contabil_card4_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Valor Lançamento.
        /// </summary>
        internal static string contabil_card4_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contábil.
        /// </summary>
        internal static string contabil_card4_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card4_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fluxo de Caixa.
        /// </summary>
        internal static string contabil_card5_btn1 {
            get {
                return ResourceManager.GetString("contabil_card5_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Extrato Financeiro.
        /// </summary>
        internal static string contabil_card5_btn2 {
            get {
                return ResourceManager.GetString("contabil_card5_btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contábil.
        /// </summary>
        internal static string contabil_card5_btn3 {
            get {
                return ResourceManager.GetString("contabil_card5_btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Limpar seleção.
        /// </summary>
        internal static string contabil_card5_btn4 {
            get {
                return ResourceManager.GetString("contabil_card5_btn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string contabil_card5_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a contrato.
        /// </summary>
        internal static string contabil_card5_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição contrato.
        /// </summary>
        internal static string contabil_card5_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contraparte.
        /// </summary>
        internal static string contabil_card5_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Índice.
        /// </summary>
        internal static string contabil_card5_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar contratos para processamento.
        /// </summary>
        internal static string contabil_card5_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card5_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/FluxoOperacional/en-US.
        /// </summary>
        internal static string contabil_content_tutorial {
            get {
                return ResourceManager.GetString("contabil_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Quando marcada, esta opção habilita o recurso de selecionar no grid vários contratos para processamento do fluxo operacional, do extrato financeiro ou do extrato contábil..
        /// </summary>
        internal static string contabil_quick_guide1 {
            get {
                return ResourceManager.GetString("contabil_quick_guide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Neste formulário são listados os contratos de aluguel que possuem verbas contratadas e/ou acessórias. Utilize os filtros (funil) para manipular a amostra de dados. Clique no título da coluna para ordenar os dados de forma ascendente ↑ ou descendente ↓. Dê um duplo clique na linha do grid para selecionar o contrato sobre o qual deseja consultar ou processar o fluxo operacional, o extrato financeiro ou o extrato contábil..
        /// </summary>
        internal static string contabil_quick_guide2 {
            get {
                return ResourceManager.GetString("contabil_quick_guide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fluxo Operacional.
        /// </summary>
        internal static string contabil_quick_guide3 {
            get {
                return ResourceManager.GetString("contabil_quick_guide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecione qual ação deseja executar sobre o contrato selecionado: fluxo operacional, extrato financeiro ou extrato contábil..
        /// </summary>
        internal static string contabil_quick_guide4 {
            get {
                return ResourceManager.GetString("contabil_quick_guide4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Clique no botão PROCESSAR para executar o fluxo operacional, o extrato financeiro ou o extrato contábil. Especificamente para o extrato financeiro, quando a data limite não estiver anotada, o extrato é executado até o final da vigência do contrato. Especificamente para o extrato contábil, quando a data limite não estiver anotada, o contábil é executado até o último lançamento registrado no extrato financeiro..
        /// </summary>
        internal static string contabil_quick_guide5 {
            get {
                return ResourceManager.GetString("contabil_quick_guide5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Clique com o botão direito do mouse sobre o grid para exportar a coleção de dados nos formatos CSV (“Comma-Separated-Values“ suportado pelos aplicativos Microsoft Excel, Google Sheets, Apple Numbers, OpenOffice Calc, LibreOffice) ou XLSX (Microsoft Excel). Escolha a opção ATUALIZAR (refresh) para mostrar no grid a última versão da coleção de dados gravada na database..
        /// </summary>
        internal static string contabil_quick_guide6 {
            get {
                return ResourceManager.GetString("contabil_quick_guide6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ao selecionar o contrato os campos serão preenchidos com as informações do Código do Contrato, o Índice utilizado no contrato, a Descrição do contrato utilizada para classificação e o Fornecedor associado ao Contrato..
        /// </summary>
        internal static string contabil_quick_guide7 {
            get {
                return ResourceManager.GetString("contabil_quick_guide7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Permitir multi seleção.
        /// </summary>
        internal static string contabil_right_checkbox1 {
            get {
                return ResourceManager.GetString("contabil_right_checkbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Saldo.
        /// </summary>
        internal static string contabil_right_checkbox2 {
            get {
                return ResourceManager.GetString("contabil_right_checkbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Extrato.
        /// </summary>
        internal static string contabil_right_checkbox3 {
            get {
                return ResourceManager.GetString("contabil_right_checkbox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contratos.
        /// </summary>
        internal static string contabil_right_combo1 {
            get {
                return ResourceManager.GetString("contabil_right_combo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fluxo Operacional.
        /// </summary>
        internal static string contabil_right_combo2 {
            get {
                return ResourceManager.GetString("contabil_right_combo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Extrato Financeiro.
        /// </summary>
        internal static string contabil_right_combo3 {
            get {
                return ResourceManager.GetString("contabil_right_combo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contábil.
        /// </summary>
        internal static string contabil_right_combo4 {
            get {
                return ResourceManager.GetString("contabil_right_combo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Rescisão.
        /// </summary>
        internal static string contabil_right_combo5 {
            get {
                return ResourceManager.GetString("contabil_right_combo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Repactuação.
        /// </summary>
        internal static string contabil_right_combo6 {
            get {
                return ResourceManager.GetString("contabil_right_combo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data:.
        /// </summary>
        internal static string contabil_right_date {
            get {
                return ResourceManager.GetString("contabil_right_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Processar.
        /// </summary>
        internal static string contabil_right_main_btn {
            get {
                return ResourceManager.GetString("contabil_right_main_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data de Repactuação.
        /// </summary>
        internal static string contabil_right_repact_date {
            get {
                return ResourceManager.GetString("contabil_right_repact_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Taxa de Repactuação.
        /// </summary>
        internal static string contabil_right_repact_taxa {
            get {
                return ResourceManager.GetString("contabil_right_repact_taxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data de Rescisão.
        /// </summary>
        internal static string contabil_right_rescisao_date {
            get {
                return ResourceManager.GetString("contabil_right_rescisao_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Multa Rescisória.
        /// </summary>
        internal static string contabil_right_rescisao_valor {
            get {
                return ResourceManager.GetString("contabil_right_rescisao_valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ações do usuário.
        /// </summary>
        internal static string contabil_right_titulo1 {
            get {
                return ResourceManager.GetString("contabil_right_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modo Processamento.
        /// </summary>
        internal static string contabil_right_titulo2 {
            get {
                return ResourceManager.GetString("contabil_right_titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Navegação.
        /// </summary>
        internal static string contabil_right_titulo3 {
            get {
                return ResourceManager.GetString("contabil_right_titulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Operações do Contrato.
        /// </summary>
        internal static string contabil_tituloPag {
            get {
                return ResourceManager.GetString("contabil_tituloPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a # OPIDCONT.
        /// </summary>
        internal static string contabil_top1 {
            get {
                return ResourceManager.GetString("contabil_top1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Código Contrato.
        /// </summary>
        internal static string contabil_top2 {
            get {
                return ResourceManager.GetString("contabil_top2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Índice.
        /// </summary>
        internal static string contabil_top3 {
            get {
                return ResourceManager.GetString("contabil_top3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string contabil_top4 {
            get {
                return ResourceManager.GetString("contabil_top4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fornecedor.
        /// </summary>
        internal static string contabil_top5 {
            get {
                return ResourceManager.GetString("contabil_top5", resourceCulture);
            }
        }
    }
}
