//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PassivosAquisicao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PassivosAquisicao() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PassivosAquisicao", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string contabil_card1_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Number.
        /// </summary>
        internal static string contabil_card1_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string contabil_card1_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Supplier.
        /// </summary>
        internal static string contabil_card1_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Index.
        /// </summary>
        internal static string contabil_card1_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Legal Entity.
        /// </summary>
        internal static string contabil_card1_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Product.
        /// </summary>
        internal static string contabil_card1_coluna7 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Auxiliary Number.
        /// </summary>
        internal static string contabil_card1_coluna8 {
            get {
                return ResourceManager.GetString("contabil_card1_coluna8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contracts.
        /// </summary>
        internal static string contabil_card1_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card1_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Event.
        /// </summary>
        internal static string contabil_card2_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Spread.
        /// </summary>
        internal static string contabil_card2_coluna10 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Venc1.
        /// </summary>
        internal static string contabil_card2_coluna11 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Venc2.
        /// </summary>
        internal static string contabil_card2_coluna12 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fees.
        /// </summary>
        internal static string contabil_card2_coluna13 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        internal static string contabil_card2_coluna14 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Payment.
        /// </summary>
        internal static string contabil_card2_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nr..
        /// </summary>
        internal static string contabil_card2_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Seq.
        /// </summary>
        internal static string contabil_card2_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Days.
        /// </summary>
        internal static string contabil_card2_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Debtor.
        /// </summary>
        internal static string contabil_card2_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Amortization.
        /// </summary>
        internal static string contabil_card2_coluna7 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Interests.
        /// </summary>
        internal static string contabil_card2_coluna8 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Commission.
        /// </summary>
        internal static string contabil_card2_coluna9 {
            get {
                return ResourceManager.GetString("contabil_card2_coluna9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cash Flow.
        /// </summary>
        internal static string contabil_card2_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card2_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Event.
        /// </summary>
        internal static string contabil_card3_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string contabil_card3_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Debit.
        /// </summary>
        internal static string contabil_card3_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Credit.
        /// </summary>
        internal static string contabil_card3_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Debt Balance.
        /// </summary>
        internal static string contabil_card3_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Liabilities.
        /// </summary>
        internal static string contabil_card3_coluna5_2 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna5.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Main Balance.
        /// </summary>
        internal static string contabil_card3_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Right of use.
        /// </summary>
        internal static string contabil_card3_coluna6_2 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna6.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Quotation.
        /// </summary>
        internal static string contabil_card3_coluna7 {
            get {
                return ResourceManager.GetString("contabil_card3_coluna7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Financial Statement.
        /// </summary>
        internal static string contabil_card3_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card3_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Event.
        /// </summary>
        internal static string contabil_card4_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a D/C.
        /// </summary>
        internal static string contabil_card4_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Account Number.
        /// </summary>
        internal static string contabil_card4_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string contabil_card4_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modality.
        /// </summary>
        internal static string contabil_card4_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string contabil_card4_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card4_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accounting Statement.
        /// </summary>
        internal static string contabil_card4_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card4_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cash Flow.
        /// </summary>
        internal static string contabil_card5_btn1 {
            get {
                return ResourceManager.GetString("contabil_card5_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Financial Statement.
        /// </summary>
        internal static string contabil_card5_btn2 {
            get {
                return ResourceManager.GetString("contabil_card5_btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accounting Statement.
        /// </summary>
        internal static string contabil_card5_btn3 {
            get {
                return ResourceManager.GetString("contabil_card5_btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Limpar seleção.
        /// </summary>
        internal static string contabil_card5_btn4 {
            get {
                return ResourceManager.GetString("contabil_card5_btn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string contabil_card5_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Number.
        /// </summary>
        internal static string contabil_card5_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string contabil_card5_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Supplier.
        /// </summary>
        internal static string contabil_card5_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Index.
        /// </summary>
        internal static string contabil_card5_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Corporate.
        /// </summary>
        internal static string contabil_card5_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Product.
        /// </summary>
        internal static string contabil_card5_coluna7 {
            get {
                return ResourceManager.GetString("contabil_card5_coluna7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select contracts for processing.
        /// </summary>
        internal static string contabil_card5_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card5_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Country ID.
        /// </summary>
        internal static string contabil_card6_coluna1 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Event.
        /// </summary>
        internal static string contabil_card6_coluna10 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Debit/Credit.
        /// </summary>
        internal static string contabil_card6_coluna11 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Account Number.
        /// </summary>
        internal static string contabil_card6_coluna12 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Account Description.
        /// </summary>
        internal static string contabil_card6_coluna13 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modality ID.
        /// </summary>
        internal static string contabil_card6_coluna14 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modality.
        /// </summary>
        internal static string contabil_card6_coluna15 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Currency ID.
        /// </summary>
        internal static string contabil_card6_coluna16 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Currency.
        /// </summary>
        internal static string contabil_card6_coluna17 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Currency ID.
        /// </summary>
        internal static string contabil_card6_coluna18 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Currency.
        /// </summary>
        internal static string contabil_card6_coluna19 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Country.
        /// </summary>
        internal static string contabil_card6_coluna2 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Debit.
        /// </summary>
        internal static string contabil_card6_coluna20 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Credit.
        /// </summary>
        internal static string contabil_card6_coluna21 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a D/C Value.
        /// </summary>
        internal static string contabil_card6_coluna22 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cost Center ID.
        /// </summary>
        internal static string contabil_card6_coluna23 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cost Center.
        /// </summary>
        internal static string contabil_card6_coluna24 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Profit Center ID.
        /// </summary>
        internal static string contabil_card6_coluna25 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Profit Center.
        /// </summary>
        internal static string contabil_card6_coluna26 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Transaction Currency.
        /// </summary>
        internal static string contabil_card6_coluna27 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Creation Date.
        /// </summary>
        internal static string contabil_card6_coluna28 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Processing Date.
        /// </summary>
        internal static string contabil_card6_coluna29 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Legal Entity ID.
        /// </summary>
        internal static string contabil_card6_coluna3 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string contabil_card6_coluna30 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pending.
        /// </summary>
        internal static string contabil_card6_coluna30_1 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna30.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Processed.
        /// </summary>
        internal static string contabil_card6_coluna30_2 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna30.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string contabil_card6_coluna30_3 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna30.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Log Error.
        /// </summary>
        internal static string contabil_card6_coluna31 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Version.
        /// </summary>
        internal static string contabil_card6_coluna32 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Document Number.
        /// </summary>
        internal static string contabil_card6_coluna33 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Legal Entity.
        /// </summary>
        internal static string contabil_card6_coluna4 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Internal ID.
        /// </summary>
        internal static string contabil_card6_coluna5 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Number.
        /// </summary>
        internal static string contabil_card6_coluna6 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Auxiliary Number.
        /// </summary>
        internal static string contabil_card6_coluna7 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Portfolio.
        /// </summary>
        internal static string contabil_card6_coluna8 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Year.Month.
        /// </summary>
        internal static string contabil_card6_coluna9 {
            get {
                return ResourceManager.GetString("contabil_card6_coluna9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accounting Process.
        /// </summary>
        internal static string contabil_card6_titulo1 {
            get {
                return ResourceManager.GetString("contabil_card6_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Internal ID.
        /// </summary>
        internal static string contabil_card7_col1 {
            get {
                return ResourceManager.GetString("contabil_card7_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Period.
        /// </summary>
        internal static string contabil_card7_col2 {
            get {
                return ResourceManager.GetString("contabil_card7_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closing.
        /// </summary>
        internal static string contabil_card7_col3 {
            get {
                return ResourceManager.GetString("contabil_card7_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closed.
        /// </summary>
        internal static string contabil_card7_col3_1 {
            get {
                return ResourceManager.GetString("contabil_card7_col3.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Open.
        /// </summary>
        internal static string contabil_card7_col3_2 {
            get {
                return ResourceManager.GetString("contabil_card7_col3.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Period Closing.
        /// </summary>
        internal static string contabil_card7_titulo {
            get {
                return ResourceManager.GetString("contabil_card7_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/FluxoIFRS/en-US.
        /// </summary>
        internal static string contabil_content_tutorial {
            get {
                return ResourceManager.GetString("contabil_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Please, select a business day..
        /// </summary>
        internal static string contabil_msg_erro1 {
            get {
                return ResourceManager.GetString("contabil_msg_erro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Please, select a date before today..
        /// </summary>
        internal static string contabil_msg_erro2 {
            get {
                return ResourceManager.GetString("contabil_msg_erro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Previous month have no closing..
        /// </summary>
        internal static string contabil_msg_erro3 {
            get {
                return ResourceManager.GetString("contabil_msg_erro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selected date have closing..
        /// </summary>
        internal static string contabil_msg_erro4 {
            get {
                return ResourceManager.GetString("contabil_msg_erro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a When checked, this option enables the feature to select from the grid several contracts for processing cash flow, financial statement, accounting statement, contract termination or renegotiation of fees..
        /// </summary>
        internal static string contabil_quick_guide1 {
            get {
                return ResourceManager.GetString("contabil_quick_guide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a This form lists the contracts covered by IFRS16. Use the filters (funnel) to manipulate the sample data. Click on the column title to sort the data in ascending ↑ or descending ↓ order. Double-click on the grid line to select the contract for which you want to consult or process the cash flow, financial statement or accounting statement..
        /// </summary>
        internal static string contabil_quick_guide2 {
            get {
                return ResourceManager.GetString("contabil_quick_guide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select which action you want to perform on the selected contract: cash flow, financial statement, accounting statement, contract termination or renegotiation of fees. Then choose the applicable scenario, which can be REAL, NOMINAL, INFLATED, CURRENCY and USGAAP. These scenarios are parameterized in the system according to the use license agreement signed with NESTA..
        /// </summary>
        internal static string contabil_quick_guide3 {
            get {
                return ResourceManager.GetString("contabil_quick_guide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a After selecting the contract and the respective applicable scenario, click on the PROCESS button to execute the cash flow, financial statement, accounting statement, contract termination or renegotiation of fees. When present, the processes are executed simultaneously in the REAL, NOMINAL and INFLATED scenarios. Specifically for the financial statement, when the deadline is not noted, the statement is executed until the end of the contract term. Specifically for the accounting statement, when the deadline i [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string contabil_quick_guide4 {
            get {
                return ResourceManager.GetString("contabil_quick_guide4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Right-click on the grid to export the data collection in CSV (&quot;Comma-Separated-Values&quot; formats supported by Microsoft Excel, Google Sheets, Apple Numbers, OpenOffice Calc, LibreOffice) or XLSX (Microsoft Excel) . Choose the Refresh option to show in the grid the latest version of the data collection recorded in the database..
        /// </summary>
        internal static string contabil_quick_guide5 {
            get {
                return ResourceManager.GetString("contabil_quick_guide5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a This form lists the contracts covered by IFRS16. Use the filters (funnel) to manipulate the sample data. Click on the column title to sort the data in ascending ↑ or descending ↓ order. Double-click on the grid line to select the contract for which you want to consult or process the cash flow, financial statement or accounting statement..
        /// </summary>
        internal static string contabil_quick_guide6 {
            get {
                return ResourceManager.GetString("contabil_quick_guide6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a When selecting the contract, the fields will be filled with the information from the Contract Code, the Index used in the contract, the Contract Description used for classification and the Supplier associated with the Contract..
        /// </summary>
        internal static string contabil_quick_guide7 {
            get {
                return ResourceManager.GetString("contabil_quick_guide7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Choose the scenario on which you want to view the selected contract cash flow, financial statement or accounting statement. The scenarios can be REAL (contract currency), NOMINAL, INFLATION, CURRENCY (functional currency) and USGAAP. These scenarios are parameterized in the system according to the license agreement signed with NESTA..
        /// </summary>
        internal static string contabil_quick_guide8 {
            get {
                return ResourceManager.GetString("contabil_quick_guide8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Allow multi selection.
        /// </summary>
        internal static string contabil_right_checkbox1 {
            get {
                return ResourceManager.GetString("contabil_right_checkbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Balance.
        /// </summary>
        internal static string contabil_right_checkbox2 {
            get {
                return ResourceManager.GetString("contabil_right_checkbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Statement.
        /// </summary>
        internal static string contabil_right_checkbox3 {
            get {
                return ResourceManager.GetString("contabil_right_checkbox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closure.
        /// </summary>
        internal static string contabil_right_checkbox4 {
            get {
                return ResourceManager.GetString("contabil_right_checkbox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Reopening.
        /// </summary>
        internal static string contabil_right_checkbox5 {
            get {
                return ResourceManager.GetString("contabil_right_checkbox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contracts.
        /// </summary>
        internal static string contabil_right_combo1 {
            get {
                return ResourceManager.GetString("contabil_right_combo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a IFRS Cash Flow.
        /// </summary>
        internal static string contabil_right_combo2 {
            get {
                return ResourceManager.GetString("contabil_right_combo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Financial Statement.
        /// </summary>
        internal static string contabil_right_combo3 {
            get {
                return ResourceManager.GetString("contabil_right_combo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accounting Statement.
        /// </summary>
        internal static string contabil_right_combo4 {
            get {
                return ResourceManager.GetString("contabil_right_combo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Termination.
        /// </summary>
        internal static string contabil_right_combo5 {
            get {
                return ResourceManager.GetString("contabil_right_combo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Renegotiation.
        /// </summary>
        internal static string contabil_right_combo6 {
            get {
                return ResourceManager.GetString("contabil_right_combo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Period Closing.
        /// </summary>
        internal static string contabil_right_combo7 {
            get {
                return ResourceManager.GetString("contabil_right_combo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accounting Integration.
        /// </summary>
        internal static string contabil_right_combo8 {
            get {
                return ResourceManager.GetString("contabil_right_combo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Date:.
        /// </summary>
        internal static string contabil_right_date {
            get {
                return ResourceManager.GetString("contabil_right_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Process.
        /// </summary>
        internal static string contabil_right_main_btn {
            get {
                return ResourceManager.GetString("contabil_right_main_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accounting Period.
        /// </summary>
        internal static string contabil_right_processo_date {
            get {
                return ResourceManager.GetString("contabil_right_processo_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Renegotiation Date.
        /// </summary>
        internal static string contabil_right_repact_date {
            get {
                return ResourceManager.GetString("contabil_right_repact_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Renegotiation Rate.
        /// </summary>
        internal static string contabil_right_repact_taxa {
            get {
                return ResourceManager.GetString("contabil_right_repact_taxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Termination Date.
        /// </summary>
        internal static string contabil_right_rescisao_date {
            get {
                return ResourceManager.GetString("contabil_right_rescisao_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Termination Penalty.
        /// </summary>
        internal static string contabil_right_rescisao_valor {
            get {
                return ResourceManager.GetString("contabil_right_rescisao_valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User actions.
        /// </summary>
        internal static string contabil_right_titulo1 {
            get {
                return ResourceManager.GetString("contabil_right_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Processing Mode.
        /// </summary>
        internal static string contabil_right_titulo2 {
            get {
                return ResourceManager.GetString("contabil_right_titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Navigation.
        /// </summary>
        internal static string contabil_right_titulo3 {
            get {
                return ResourceManager.GetString("contabil_right_titulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Operations.
        /// </summary>
        internal static string contabil_tituloPag {
            get {
                return ResourceManager.GetString("contabil_tituloPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a # OPIDCONT.
        /// </summary>
        internal static string contabil_top1 {
            get {
                return ResourceManager.GetString("contabil_top1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Number.
        /// </summary>
        internal static string contabil_top2 {
            get {
                return ResourceManager.GetString("contabil_top2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string contabil_top3 {
            get {
                return ResourceManager.GetString("contabil_top3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Supplier.
        /// </summary>
        internal static string contabil_top4 {
            get {
                return ResourceManager.GetString("contabil_top4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Currency.
        /// </summary>
        internal static string contabil_top5 {
            get {
                return ResourceManager.GetString("contabil_top5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exchange Currency.
        /// </summary>
        internal static string contabil_top6 {
            get {
                return ResourceManager.GetString("contabil_top6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Functional Currency.
        /// </summary>
        internal static string contabil_top7 {
            get {
                return ResourceManager.GetString("contabil_top7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Currency.
        /// </summary>
        internal static string filtro_grid_CONTABILIZAMOEDA {
            get {
                return ResourceManager.GetString("filtro_grid_CONTABILIZAMOEDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inflation.
        /// </summary>
        internal static string filtro_grid_CVM_INFLACIONADO {
            get {
                return ResourceManager.GetString("filtro_grid_CVM_INFLACIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nominal.
        /// </summary>
        internal static string filtro_grid_CVM_NOMINAL {
            get {
                return ResourceManager.GetString("filtro_grid_CVM_NOMINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Real.
        /// </summary>
        internal static string filtro_grid_CVM_REAL {
            get {
                return ResourceManager.GetString("filtro_grid_CVM_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a USGAAP.
        /// </summary>
        internal static string filtro_grid_USGAAP {
            get {
                return ResourceManager.GetString("filtro_grid_USGAAP", resourceCulture);
            }
        }
    }
}
