//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Relatorios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Relatorios() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Relatorios", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Refresh.
        /// </summary>
        internal static string relatorio_header_link {
            get {
                return ResourceManager.GetString("relatorio_header_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Report Parameters.
        /// </summary>
        internal static string relatorio_popup2_titulo {
            get {
                return ResourceManager.GetString("relatorio_popup2_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Dimensions of Report.
        /// </summary>
        internal static string relatorio_popup_titulo {
            get {
                return ResourceManager.GetString("relatorio_popup_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Export.
        /// </summary>
        internal static string relatorio_right_btn1 {
            get {
                return ResourceManager.GetString("relatorio_right_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Excel.
        /// </summary>
        internal static string relatorio_right_checkbox1 {
            get {
                return ResourceManager.GetString("relatorio_right_checkbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Excel (Data Aware).
        /// </summary>
        internal static string relatorio_right_checkbox2 {
            get {
                return ResourceManager.GetString("relatorio_right_checkbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a PDF.
        /// </summary>
        internal static string relatorio_right_checkbox3 {
            get {
                return ResourceManager.GetString("relatorio_right_checkbox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Load Layout.
        /// </summary>
        internal static string relatorio_right_grid_btn1 {
            get {
                return ResourceManager.GetString("relatorio_right_grid_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Save Layout.
        /// </summary>
        internal static string relatorio_right_grid_btn2 {
            get {
                return ResourceManager.GetString("relatorio_right_grid_btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pivot.
        /// </summary>
        internal static string relatorio_right_opt1 {
            get {
                return ResourceManager.GetString("relatorio_right_opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Table.
        /// </summary>
        internal static string relatorio_right_opt2 {
            get {
                return ResourceManager.GetString("relatorio_right_opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type of Exporting.
        /// </summary>
        internal static string relatorio_right_subtitulo1 {
            get {
                return ResourceManager.GetString("relatorio_right_subtitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select.
        /// </summary>
        internal static string relatorio_right_subtitulo2 {
            get {
                return ResourceManager.GetString("relatorio_right_subtitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Layout Loaded.
        /// </summary>
        internal static string relatorio_right_subtitulo3 {
            get {
                return ResourceManager.GetString("relatorio_right_subtitulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a View.
        /// </summary>
        internal static string relatorio_right_titulo {
            get {
                return ResourceManager.GetString("relatorio_right_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Dimensions.
        /// </summary>
        internal static string relatorio_right_titulo1 {
            get {
                return ResourceManager.GetString("relatorio_right_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Exporting.
        /// </summary>
        internal static string relatorio_right_titulo2 {
            get {
                return ResourceManager.GetString("relatorio_right_titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Layout.
        /// </summary>
        internal static string relatorio_right_titulo3 {
            get {
                return ResourceManager.GetString("relatorio_right_titulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a View.
        /// </summary>
        internal static string relatorio_right_titulo4 {
            get {
                return ResourceManager.GetString("relatorio_right_titulo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selected Report:.
        /// </summary>
        internal static string relatorio_titulo {
            get {
                return ResourceManager.GetString("relatorio_titulo", resourceCulture);
            }
        }
    }
}
