//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Verbas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Verbas() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Verbas", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select.
        /// </summary>
        internal static string verbas_combo1_item1 {
            get {
                return ResourceManager.GetString("verbas_combo1_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string verbas_combo1_item2 {
            get {
                return ResourceManager.GetString("verbas_combo1_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string verbas_combo1_item3 {
            get {
                return ResourceManager.GetString("verbas_combo1_item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contracted.
        /// </summary>
        internal static string verbas_combo3_item1 {
            get {
                return ResourceManager.GetString("verbas_combo3_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Accessory.
        /// </summary>
        internal static string verbas_combo3_item2 {
            get {
                return ResourceManager.GetString("verbas_combo3_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Permanent.
        /// </summary>
        internal static string verbas_combo4_item1 {
            get {
                return ResourceManager.GetString("verbas_combo4_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Eventual.
        /// </summary>
        internal static string verbas_combo4_item2 {
            get {
                return ResourceManager.GetString("verbas_combo4_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string verbas_combo5_item1 {
            get {
                return ResourceManager.GetString("verbas_combo5_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string verbas_combo5_item2 {
            get {
                return ResourceManager.GetString("verbas_combo5_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Monthly.
        /// </summary>
        internal static string verbas_combo6_item1 {
            get {
                return ResourceManager.GetString("verbas_combo6_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Bimonthly.
        /// </summary>
        internal static string verbas_combo6_item2 {
            get {
                return ResourceManager.GetString("verbas_combo6_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Quarterly.
        /// </summary>
        internal static string verbas_combo6_item3 {
            get {
                return ResourceManager.GetString("verbas_combo6_item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Four-Monthly.
        /// </summary>
        internal static string verbas_combo6_item4 {
            get {
                return ResourceManager.GetString("verbas_combo6_item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Semester.
        /// </summary>
        internal static string verbas_combo6_item5 {
            get {
                return ResourceManager.GetString("verbas_combo6_item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Annual.
        /// </summary>
        internal static string verbas_combo6_item6 {
            get {
                return ResourceManager.GetString("verbas_combo6_item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calculated.
        /// </summary>
        internal static string verbas_combo7_item1 {
            get {
                return ResourceManager.GetString("verbas_combo7_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informed.
        /// </summary>
        internal static string verbas_combo7_item2 {
            get {
                return ResourceManager.GetString("verbas_combo7_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        internal static string verbas_combo8_item1 {
            get {
                return ResourceManager.GetString("verbas_combo8_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        internal static string verbas_combo8_item2 {
            get {
                return ResourceManager.GetString("verbas_combo8_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a https://cloud3.webnesta.com/tutorial/ifrs/verbas/en-US.
        /// </summary>
        internal static string verbas_content_tutorial {
            get {
                return ResourceManager.GetString("verbas_content_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string verbas_lbl1 {
            get {
                return ResourceManager.GetString("verbas_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Base Calculation Months.
        /// </summary>
        internal static string verbas_lbl10 {
            get {
                return ResourceManager.GetString("verbas_lbl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Indicative base in months for the calculation of the average tolerance for payments of this amount..
        /// </summary>
        internal static string verbas_lbl10_guide {
            get {
                return ResourceManager.GetString("verbas_lbl10_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calcula Impostos?.
        /// </summary>
        internal static string verbas_lbl11 {
            get {
                return ResourceManager.GetString("verbas_lbl11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select Fund.
        /// </summary>
        internal static string verbas_lbl1_direita {
            get {
                return ResourceManager.GetString("verbas_lbl1_direita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecionar a Verba que deseja visualizar, alterar ou excluir..
        /// </summary>
        internal static string verbas_lbl1_direita_guide {
            get {
                return ResourceManager.GetString("verbas_lbl1_direita_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name of the Fund, will be the name that will be available for selection and association with the contracts and in the billing operations of accounts payable..
        /// </summary>
        internal static string verbas_lbl1_guide {
            get {
                return ResourceManager.GetString("verbas_lbl1_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calculate IFRS?.
        /// </summary>
        internal static string verbas_lbl2 {
            get {
                return ResourceManager.GetString("verbas_lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select whether the Budget applies to IFRS calculation rules, information of major import for the correct accounting of contracts..
        /// </summary>
        internal static string verbas_lbl2_guide {
            get {
                return ResourceManager.GetString("verbas_lbl2_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Classifier.
        /// </summary>
        internal static string verbas_lbl3 {
            get {
                return ResourceManager.GetString("verbas_lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecting the appropriate classifier, this information can be used for filters in reports..
        /// </summary>
        internal static string verbas_lbl3_guide {
            get {
                return ResourceManager.GetString("verbas_lbl3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Fund Type.
        /// </summary>
        internal static string verbas_lbl4 {
            get {
                return ResourceManager.GetString("verbas_lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contracted: Funds that are previously noted in the contract. &lt;br/&gt; Accessory: Extra contract funds, but which are only the responsibility of the lessee (example: energy, water, etc.).
        /// </summary>
        internal static string verbas_lbl4_guide {
            get {
                return ResourceManager.GetString("verbas_lbl4_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Frequency.
        /// </summary>
        internal static string verbas_lbl5 {
            get {
                return ResourceManager.GetString("verbas_lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Permanent: Amounts that will be paid for the life of the contract, and will be provided in the payment flow. &lt;br/&gt; Eventual: The amount will be paid only in that event (Date) and will not be provided in the payment flow..
        /// </summary>
        internal static string verbas_lbl5_guide {
            get {
                return ResourceManager.GetString("verbas_lbl5_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tax Recovery.
        /// </summary>
        internal static string verbas_lbl6 {
            get {
                return ResourceManager.GetString("verbas_lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a When the property is owned by a LEGAL PERSON (COMPANY or SOCIAL ORGANIZATION) the lessee can recover taxes related to PIS and COFINS. This situation only applies in Brazil..
        /// </summary>
        internal static string verbas_lbl6_guide {
            get {
                return ResourceManager.GetString("verbas_lbl6_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Interval.
        /// </summary>
        internal static string verbas_lbl7 {
            get {
                return ResourceManager.GetString("verbas_lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select which recurrence will be paid for this amount.
        /// </summary>
        internal static string verbas_lbl7_guide {
            get {
                return ResourceManager.GetString("verbas_lbl7_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Value Mode.
        /// </summary>
        internal static string verbas_lbl8 {
            get {
                return ResourceManager.GetString("verbas_lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calculated Amount: There is a basis for the automated calculation of the payment of the Budget. &lt;br/&gt; Amount Informed: The amount is paid according to the Lessor&apos;s billing information..
        /// </summary>
        internal static string verbas_lbl8_guide {
            get {
                return ResourceManager.GetString("verbas_lbl8_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tolerance %.
        /// </summary>
        internal static string verbas_lbl9 {
            get {
                return ResourceManager.GetString("verbas_lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Percentage applied to the average amount of the Budget to determine the payment tolerance limits..
        /// </summary>
        internal static string verbas_lbl9_guide {
            get {
                return ResourceManager.GetString("verbas_lbl9_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Actions.
        /// </summary>
        internal static string verbas_titulo_direita {
            get {
                return ResourceManager.GetString("verbas_titulo_direita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funds.
        /// </summary>
        internal static string verbas_titulo_principal {
            get {
                return ResourceManager.GetString("verbas_titulo_principal", resourceCulture);
            }
        }
    }
}
